// ============================================
// 西向きベランダ菜園記録 データファイル
// 記録の追加・修正はこのファイルだけ編集すればOK
// 写真は images/ フォルダに入れてファイル名を指定
// ============================================

const SITE = {
  title: "西向きベランダで野菜を育てる記録",
  subtitle: "完全西向き、高さ140cmの壁に囲まれた東京のベランダ。\n日照制限という条件の中で、何が育ち、何が難しいのか。\n試行錯誤のリアルな栽培ログです。",
  badges: ["🧭 完全西向き", "🧱 壁高140cm", "東京都内", "プランター栽培", "2025年〜"],
  // ヒーロー写真（3枚推奨：1枚目が大きく表示される）
  heroPhotos: [
    // "hero1.jpg",
    // "hero2.jpg",
    // "hero3.jpg",
  ],
};

// サイト更新履歴（新しい順・最大10件程度を表示）
const SITE_UPDATES = [
  { date: "9/16", text: "2025年秋蒔き（そら豆・スナップエンドウ・サンチュ・秋蒔きルッコラ）を新規追加、春菊を2025年秋蒔きの実記録に更新。費用ページにこれまでの購入記録42件を追加" },
  { date: "9/16", text: "各野菜の「基本データ」「ポイント」を統一フォーマットに更新（分類・空白期間・種子・種まき/定植/収穫時期・土の性質・株間・推奨プランターなど）" },
  { date: "9/16", text: "サイト機能を追加：栽培中/年度・時期タブ＋野菜名検索＋記録内容の全文検索と連動する上部ナビ、設備セクションの折りたたみ表示、費用（購入品）ページを新設" },
  { date: "9/15", text: "バジル（四角プランター）・パセリの今期栽培終了を追加" },
  { date: "9/11", text: "曇り・雨続きの天候メモ、メロン着果25日目、唐辛子新芽整理、ニラ・紫蘇の生育、バジル・パセリの終了検討を追加" },
  { date: "9/5", text: "曇り続きの天候メモ、唐辛子・ニラ・バジル・紫蘇・パセリの液肥、メロン着果19日目（直径11cm・ひび割れ）を追加" },
  { date: "9/2", text: "紫蘇の収穫を追加" },
  { date: "9/1", text: "土再生作業（ルッコラ・モロヘイヤ・きゅうり、再生剤投入）を追加" },
  { date: "8/31", text: "ミニトマト今期栽培終了（最終3個収穫）、ニラ収穫・間引きを追加" },
  { date: "8/30", text: "メロンの着果13日目・ネット保護、ミニトマト・唐辛子・ニラ・バジル・紫蘇・パセリの生育記録を追加" },
  { date: "8/28", text: "メロン・パセリ・ニラ・バジル・紫蘇・唐辛子の液肥施行を追加" },
  { date: "8/23", text: "ミニトマトの花落ち、メロンの着果・液肥開始、バジル・紫蘇収穫、パセリ剪定、唐辛子の花落ち、ニラの生育を追加" },
  { date: "8/20", text: "メロンの受粉結果（失敗1個・成功の可能性1個）、パセリの新葉、土再生作業（モロヘイヤ・ルッコラ・きゅうり）を追加" },
  { date: "8/18", text: "ミニトマト5個収穫（今期累計20個）を追加" },
  { date: "8/16", text: "唐辛子3本仕立てに剪定、全体の毎晩葉水記録、紫蘇の液肥、ミニトマト・メロンの生育記録、ニラの生育、パセリの葉色不良の原因判明（ハダニ）、バジルの液肥記録を追加" },
  { date: "8/8", text: "メロン雄花開花、ニラ回復、バジル・紫蘇液肥、唐辛子の8/8記録を追加" },
  { date: "8/7", text: "バジル収穫、ミニトマト8個収穫（今期累計15個）を追加" },
  { date: "8/6", text: "バジル・紫蘇の収穫（8/6）を追加" },
  { date: "8/2", text: "唐辛子5個収穫、パセリ・ニラ・メロン・バジル・ミニトマト・紫蘇の8/2記録を追加" },
  { date: "7/27", text: "パセリ・ニラの生育記録を追加" },
  { date: "7/27", text: "唐辛子の回復、メロン・バジルの生育写真を追加" },
  { date: "7/27", text: "ミニトマト2個収穫・葉ダニ再発、きゅうり今期栽培終了、紫蘇ハダニ剪定を追加" },
  { date: "7/26", text: "唐辛子の水切れ・回復記録、ダニ太郎の効果メモを追加" },
  { date: "7/24", text: "唐辛子3個収穫（今期累計5個）を追加" },
  { date: "7/23", text: "唐辛子の猛暑による水切れ・萎れを記録" },
  { date: "7/21", text: "唐辛子4/29の写真を追加" },
  { date: "7/21", text: "ニラ・パセリ・バジル・ルッコラの5/11写真を追加" },
  { date: "7/20", text: "5/29分の写真（モロヘイヤ・唐辛子・紫蘇・ニラ・ミニトマト・パセリ・バジル・ルッコラ）を追加" },
  { date: "7/20", text: "全体ログに「ダニ太郎を初使用」を追加" },
];

// 環境データ
const ENV = [
  { icon: "🧭", label: "方角", value: "完全西向き" },
  { icon: "🧱", label: "壁の高さ", value: "約140cm" },
  { icon: "☀️", label: "日照時間", value: "午後のみ" },
  { icon: "🪣", label: "栽培方法", value: "プランター" },
];

// 設備・資材
const SETUP = {
  photos: [
    // { src: "setup1.jpg", caption: "プランター配置全体" },
    // { src: "setup2.jpg", caption: "スタンドで高さを確保" },
  ],
  cards: [
    {
      title: "🌿 プランタースタンド",
      items: ["サイズ：45.2 × 51.4 × 60cm", "段々式で高さを確保", "壁の影を避けるため最上段活用"],
    },
    {
      title: "🏠 虫よけビニールハウス",
      items: ["シート：1m × 1.5m × 2枚", "虫よけネット（ダイソー）1m × 1.4m", "フレーム網：52×40cm×3・52×20cm×1"],
    },
    // カードはいくつでも追加OK
  ],
};

// ============================================
// 野菜データ
// id：英数字（ページ内リンクに使われる）
// color：moss / bark / teal / olive / amber / plum から選択
// westRating：西向き適性 1〜5
// ============================================
const VEGGIES = [
  {
    id: "parsley",
    emoji: "🌿",
    name: "パセリ",
    sub: "イタリアンパセリ",
    color: "olive",
    status: "🏁 栽培終了（9/15で終了）",
    season: "2025年秋蒔き",
    westRating: 5,
    basicData: [
      { key: "分類", val: "セリ科" },
      { key: "空白期間（連作対策）", val: "1〜2年" },
      { key: "種子(好光or嫌光)", val: "好光" },
      { key: "種まき時期", val: "9〜10月" },
      { key: "定植時期", val: "10月前後" },
      { key: "収穫時期", val: "11〜翌年春" },
      { key: "最適な土の性質", val: "弱酸性〜中性、やや湿り気" },
      { key: "株間目安", val: "20〜30cm" },
      { key: "推奨プランター", val: "広め：深さ20cm～、幅30cm～" },
    ],
    points: [
      "【追肥】葉が黄色くなり始めたタイミングで施す",
      "【収穫】草丈20cm・本葉15枚以上になってから",
      "外側の葉から根元をカットして収穫",
      "常に10本以上の葉を残す",
      "収穫後は1,000倍に薄めた液肥を週1回施す",
    ],
    warnings: [
      "葉が黄色くなり始めたら追肥のサイン",
    ],
    westNote: "西向きでも半日陰に強いパセリは旺盛に生育。種まきから越冬して2年目に入り安定した収穫が続いている。",
    photos: [
      "parsley_240616_3.jpg",
      "parsley_240616_1.jpg",
    ],
    timeline: [
      { date: "10/3夜", tags: ["seed"], title: "種を水に浸す", text: "一晩水に浸して発芽を促す。好光性種子のため翌日の種まき後は遮光しない。", photos: [] },
      { date: "10/4", tags: ["seed"], title: "小鉢×2に種まき", text: "2つの小鉢に種をまく。", photos: [] },
      { date: "10/15〜16", tags: ["grow"], title: "発芽確認", text: "種まきから約11日で発芽が始まった。", photos: [] },
      { date: "11/23", tags: ["grow"], title: "定植（4株）", text: "本葉が展開した苗4株を定植。", photos: [] },
      { date: "12/9", tags: ["grow"], title: "間引いて2株に", text: "生育の良い2株を残して間引き。株間を確保し風通しを改善。", photos: [] },
      { date: "4/10", tags: ["harvest"], title: "収穫（2本）・苦味あり", text: "2本収穫。この時点でこれまでに計4本ほど収穫済み。苦味が感じられた（冬越し後の特徴）。", photos: [] },
      { date: "4/12", tags: ["grow"], title: "液肥実施", text: "", photos: [] },
      { date: "4/20", tags: ["grow"], title: "液肥実施", text: "", photos: [] },
      { date: "4/28", tags: ["harvest"], title: "収穫（3本）", text: "3本収穫。", photos: [] },
      { date: "4/29", tags: ["grow"], title: "液肥・葉面散布", text: "液肥の通常施用に加え、葉面散布も実施。", photos: [] },
      {
        date: "5/11",
        tags: ["grow"],
        title: "旺盛に生育中",
        text: "葉が大きく広がり、ボリュームのある株に成長している。",
        photos: ["parsley_250511_1.jpg"],
      },
      { date: "5/12", tags: ["grow"], title: "液肥実施", text: "", photos: [] },
      { date: "5/19", tags: ["grow"], title: "液肥実施", text: "", photos: [] },
      { date: "5/28", tags: ["grow"], title: "液肥実施", text: "", photos: [] },
      {
        date: "5/29",
        tags: ["grow"],
        title: "旺盛に生育中",
        text: "葉が大きく茂り、鉢からあふれるほど旺盛に生育している。",
        photos: ["parsley_250529_1.jpg"],
      },
      { date: "6/5", tags: ["grow"], title: "液肥実施", text: "", photos: [] },
      {
        date: "6/7",
        tags: ["grow"],
        title: "旺盛に生育中",
        text: "葉が大きく広がり、ボリュームのある株に成長している。",
        photos: ["parsley_250607_1.jpg"],
      },
      { date: "6/12", tags: ["grow", "harvest"], title: "液肥実施・収穫", text: "液肥を実施するとともに収穫も行った。", photos: [] },
      {
        date: "6/16",
        tags: ["grow"],
        title: "収穫前・旺盛に生育中",
        text: "青々とした葉が鉢いっぱいに広がっている状態。",
        photos: [
          "parsley_240616_3.jpg",
          "parsley_240616_1.jpg",
          "parsley_240616_2.jpg",
        ],
      },
      {
        date: "6/16",
        tags: ["harvest"],
        title: "収穫 茎10本ほど",
        text: "外葉から茎ごと約10本収穫。収穫後も株元から新芽がしっかり残っており、次の収穫も期待できる状態。",
        photos: [
          "parsley_240616_harvest.jpg",
          "parsley_240616_after1.jpg",
          "parsley_240616_after2.jpg",
          "parsley_240616_after3.jpg",
        ],
      },
      {
        date: "6/19",
        tags: ["grow"],
        title: "液肥実施・週1ペースで管理",
        text: "6/16の収穫後から3日。新芽が再び展開してきた。液肥を実施。週1回ペースで継続予定。",
        photos: [
          "parsley_250619_1.jpg",
        ],
      },
      {
        date: "6/26",
        tags: ["harvest"],
        title: "16本ほど収穫・乾燥パセリに加工・液肥実施",
        text: "外葉から茎ごと16本ほど収穫。株全体にボリュームが出ており旺盛な生育ぶり。収穫したパセリは葉を外して乾燥させ、ビン詰め保存。収穫後に液肥を実施。",
        photos: [
          "parsley_250626_1.jpg",
          "parsley_250626_2.jpg",
          "parsley_250626_3.jpg",
          "parsley_250626_4.jpg",
          "parsley_250626_5.jpg",
        ],
      },
      {
        date: "7/2",
        tags: ["harvest"],
        title: "13本ほど収穫",
        text: "茎ごと13本ほど収穫。花瓶に生けて食卓の彩りにも。",
        photos: ["parsley_250702_1.jpg"],
      },
      {
        date: "7/4",
        tags: ["grow"],
        title: "液肥実施",
        text: "収穫後の生育を促すため液肥を実施。",
        photos: [],
      },
      {
        date: "7/12",
        tags: ["grow"],
        title: "液肥実施",
        text: "液肥を実施。葉が旺盛に茂っている。",
        photos: ["parsley_250712_1.jpg"],
      },
      {
        date: "7/15",
        tags: ["trouble", "harvest"],
        title: "白い斑点模様・収穫を兼ねて剪定",
        text: "葉に白い斑点模様が見られたため、収穫を兼ねて剪定を実施。",
        photos: ["parsley_250715_1.jpg", "parsley_250715_2.jpg"],
      },
      {
        date: "7/19",
        tags: ["trouble", "grow"],
        title: "液肥実施・葉の色が薄い",
        text: "液肥を実施。葉の色がやや薄くなってきている印象で、経過観察中。",
        photos: ["parsley_250719_1.jpg"],
      },
      {
        date: "7/27",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["parsley_250727_1.jpg"],
      },
      {
        date: "8/2",
        tags: ["trouble", "grow"],
        title: "葉の色が悪く新葉も生えない・病気の疑い・液肥実施",
        text: "葉の色が良くなく、新しい葉も生えてこない状態。病気の可能性もあり経過観察中。液肥を実施。",
        photos: ["parsley_250802_1.jpg"],
      },
      {
        date: "8/16",
        tags: ["trouble"],
        title: "葉色不良の原因はハダニと判明",
        text: "よく見るとハダニの被害だと判明した。",
        photos: ["parsley_260816_1.jpg"],
      },
      {
        date: "8/20",
        tags: ["grow"],
        title: "新しい葉が出始め・古い枯れ葉を剪定",
        text: "新しい葉が出てき始めた。古く枯れている葉を剪定。",
        photos: ["parsley_260820_1.jpg", "parsley_260820_2.jpg", "parsley_260820_3.jpg"],
      },
      {
        date: "8/23",
        tags: ["grow"],
        title: "小さな新葉が密集・剪定",
        text: "小さい葉が育ってきたが密集しているため剪定。",
        photos: ["parsley_260823_1.jpg"],
      },
      {
        date: "8/28",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。",
        photos: [],
      },
      {
        date: "8/30",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["parsley_260830_1.jpg"],
      },
      {
        date: "9/5",
        tags: ["grow", "trouble"],
        title: "液肥施行・葉が伸びるが一部白化",
        text: "液肥を施行。葉は伸びてきているが、一部白くなりつつある箇所もある。（※直近の天候は全体ログ参照）",
        photos: ["parsley_260905_1.jpg"],
      },
      {
        date: "9/11",
        tags: ["trouble"],
        title: "色の悪い葉を剪定・涼しさで伸び弱く・ハダニ様の虫と卵を顕微鏡で確認",
        text: "色が悪くなった葉を剪定。涼しくなってきたためか伸びが弱く、葉も白くなっている箇所がある。顕微鏡で葉裏を確認するとダニ様の虫やイモムシらしきもの、卵も見られた。今年の栽培を終了にするか検討中。",
        photos: [
          "parsley_260911_1.jpg",
          { src: "parsley_260911_2.jpg", sensitive: true },
          { src: "parsley_260911_3.jpg", sensitive: true },
        ],
      },
      {
        date: "9/15",
        tags: ["end"],
        title: "今期栽培終了",
        text: "ハダニ被害と涼しさによる生育の弱まりを受け、今期の栽培を終了。",
        photos: [],
      },
    ],
  },

  {
    id: "melon",
    emoji: "🍈",
    name: "メロン",
    sub: "種まきから育苗中",
    color: "amber",
    status: "🌱 栽培中",
    season: "2026年春蒔き",
    westRating: 2,
    basicData: [
      { key: "分類", val: "ウリ科" },
      { key: "空白期間（連作対策）", val: "3〜4年" },
      { key: "種子(好光or嫌光)", val: "嫌光" },
      { key: "種まき時期", val: "4〜5月" },
      { key: "定植時期", val: "5月" },
      { key: "収穫時期", val: "7〜8月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、深く、有機質豊か" },
      { key: "株間目安", val: "60〜80cm（1本／プランター）" },
      { key: "推奨プランター", val: "深め：深さ30cm～" },
    ],
    points: [
      "種まきの深さは1cm",
      "本葉2〜3枚で間引き（根が繊細なためハサミで切る）",
      "本葉3〜4枚で定植",
      "本葉5〜6枚で親づるを摘芯",
      "脇から出た子ヅルを2本伸ばし、他は摘み取る",
      "子づるの8枚目までの脇芽は摘む",
      "子づるは15〜20節位までで摘心",
      "受粉は午前8時までに（2025年は受粉させなくても肥大した実績あり）",
      "下の方の黄変した葉は切る",
      "着果節以外の孫づるは葉を1〜2枚残して切る",
      "【追肥】着果してピンポン玉大になったら化成肥料10g程度、その後は様子を見ながら2週間おきに10gずつ",
      "1ツル1果が良さそう。1株で最大3果まで",
      "収穫2週間前から水を絞ると甘くなる",
      "【収穫】目安は着果から45〜50日程度",
      "果実がついている節周辺の葉が黄変・枯れ始めたら収穫のサイン",
      "お尻（花落ち部）周辺に小さなひび割れ（コルク化）が出たり、甘い香りがしてきたら収穫時期",
    ],
    warnings: [
      "下の方の黄変した葉はこまめに除去",
      "2025年は受粉させなくても大きくなった（要記録）",
    ],
    westNote: "西向きでは日照不足が心配だが、チャレンジ中。着果・肥大のデータを記録して来年に活かす。",
    photos: [
      "melon_250621_1.jpg",
      "melon_250621_3.jpg",
    ],
    timeline: [
      { date: "5/21", tags: ["seed"], title: "小ポット×3に種まき（深さ1cm）", text: "3つの小ポットに種をまく。深さ1cm。", photos: [] },
      { date: "5/31", tags: ["grow"], title: "発芽確認・複数の芽", text: "複数の芽が出始めた。", photos: [] },
      { date: "6/2", tags: ["grow"], title: "間引き・2株以下/ポットに", text: "根が繊細なためハサミで間引き。各ポット2株以下に。", photos: ["melon_250602_1.jpg"] },
      {
        date: "6/7",
        tags: ["grow"],
        title: "双葉の状態・育苗順調",
        text: "3つのポットそれぞれで双葉がしっかり開いている。順調に育苗中。",
        photos: ["melon_250607_1.jpg"],
      },
      {
        date: "6/15",
        tags: ["grow"],
        title: "本葉1枚しっかり展開",
        text: "本葉が1枚しっかり展開。白ポット1株・黒ポット2株の計3株が順調に育苗中。",
        photos: ["melon_250615_1.jpg"],
      },
      {
        date: "6/19",
        tags: ["grow"],
        title: "本葉2枚しっかり展開・定植間近",
        text: "本葉2枚がしっかり展開。定植の目安（本葉3〜4枚）まであと少し。",
        photos: ["melon_250619_1.jpg"],
      },
      {
        date: "6/21",
        tags: ["grow"],
        title: "本葉3枚目展開・定植＆支柱設置",
        text: "本葉3枚目が出始めたタイミングで定植を実施。支柱も設置して誘引開始。",
        photos: ["melon_250621_1.jpg", "melon_250621_2.jpg", "melon_250621_3.jpg"],
      },
      {
        date: "7/5",
        tags: ["grow"],
        title: "本葉5枚目展開",
        text: "本葉5枚目が展開。着実に生育が進んでいる。",
        photos: ["melon_250705_1.jpg"],
      },
      {
        date: "7/10",
        tags: ["grow"],
        title: "主枝を摘芯",
        text: "主枝を摘芯。子づるの発生を促し、収穫に向けた仕立てへ移行。",
        photos: ["melon_250710_1.jpg"],
      },
      {
        date: "7/19",
        tags: ["grow"],
        title: "脇芽がしっかり伸びる",
        text: "摘芯後の脇芽がしっかりと伸びてきた。",
        photos: ["melon_250719_1.jpg"],
      },
      {
        date: "7/27",
        tags: ["grow"],
        title: "4・5節目の子づるが伸長",
        text: "4節目・5節目の側枝（子づる）が伸びてきている。",
        photos: ["melon_250727_1.jpg"],
      },
      {
        date: "8/2",
        tags: ["grow"],
        title: "網目3.5個分成長",
        text: "前回から網目3.5個分成長した。",
        photos: ["melon_250802_1.jpg"],
      },
      {
        date: "8/8",
        tags: ["flower", "grow"],
        title: "子づる10節目の根元で雄花開花・脇芽整理",
        text: "子づるの10枚目の葉の根元で雄花が開花した。本葉8枚目までの脇芽等を摘んだ。",
        photos: ["melon_250808_1.jpg", "melon_250808_2.jpg"],
      },
      {
        date: "8/13",
        tags: ["flower"],
        title: "雌花初開花・人工授粉を実施",
        text: "雌花が初めて開花。雄花を切り取り、人工授粉を試みた。",
        photos: ["melon_250813_1.jpg", "melon_250813_2.jpg", "melon_250813_3.jpg"],
      },
      {
        date: "8/16",
        tags: ["grow"],
        title: "子づる2本が19枚に・摘心予定",
        text: "二つの子づるの葉が19枚になったので、明日あたりに摘心予定。",
        photos: ["melon_260816_1.jpg"],
      },
      {
        date: "8/20",
        tags: ["trouble", "flower"],
        title: "受粉失敗1個・成功の可能性1個",
        text: "8/13の人工授粉について、1つは花がしぼんで枯れており受粉失敗と思われる。もう1つは根元が膨らみ始めており、受粉成功の可能性がある。引き続き経過観察。",
        photos: ["melon_260820_1.jpg", "melon_260820_2.jpg"],
      },
      {
        date: "8/23",
        tags: ["grow"],
        title: "着果順調に肥大・液肥を初試行",
        text: "受粉成功と思われた実がひとまず順調に大きくなっている。8/17頃の受粉なので着果6日目くらい。この実を1つ目としてカウントし、以後は着果からの日数で記録していく。ピンポン玉大になったため、今年は液肥を試してみることに。以後は様子を見ながら週1回のペース。例年は化成肥料10gを2週に1回のペースで施行していた。",
        photos: ["melon_260823_1.jpg", "melon_260823_2.jpg", "melon_260823_3.jpg"],
      },
      {
        date: "8/28",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。",
        photos: [],
      },
      {
        date: "8/30",
        tags: ["grow"],
        title: "着果13日目・ネットで保護",
        text: "1つ目の実は着果13日目（8/17頃受粉）。順調に肥大しており、ネットをかけて保護。",
        photos: ["melon_260830_1.jpg", "melon_260830_2.jpg"],
      },
      {
        date: "9/5",
        tags: ["grow", "trouble"],
        title: "液肥施行・着果19日目・直径11cm・ひび割れあり",
        text: "液肥を施行。1つ目の実は着果19日目、直径11cmほどに成長。ひび割れも見られる。今年はこの1果のみになりそう。（※直近の天候は全体ログ参照）",
        photos: ["melon_260905_1.jpg", "melon_260905_2.jpg", "melon_260905_3.jpg"],
      },
      {
        date: "9/11",
        tags: ["grow", "trouble"],
        title: "着果25日目・ひび割れ目立つ・液肥施行",
        text: "着果25日目（8/17頃受粉）。ひび割れが目立ってきた。液肥を施行。（※直近の天候は全体ログ参照）",
        photos: ["melon_260911_1.jpg", "melon_260911_2.jpg"],
      },
    ],
  },

  {
    id: "moroheiya",
    emoji: "🌿",
    name: "モロヘイヤ",
    sub: "そら豆の後作",
    color: "moss",
    status: "🥀 栽培終了（失敗）",
    season: "2026年春蒔き",
    basicData: [
      { key: "分類", val: "アオイ科" },
      { key: "空白期間（連作対策）", val: "2〜3年" },
      { key: "種子(好光or嫌光)", val: "嫌光" },
      { key: "種まき時期", val: "4〜6月" },
      { key: "定植時期", val: "5〜6月" },
      { key: "収穫時期", val: "7〜10月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、水はけよく肥料多く" },
      { key: "株間目安", val: "30〜40cm" },
      { key: "推奨プランター", val: "バランス：深さ25cm～、幅30cm～" },
    ],
    points: [
      "【種まき】5月下旬から、ポットに2〜3粒・深さ0.5〜1cm",
      "本葉4〜5枚で定植",
      "発芽適温は25〜30℃。気温がしっかり上がった5月下旬に播くのが良い",
      "植え付けから1ヶ月ごとに追肥",
      "高さ40cmで摘芯",
      "花は見つけ次第摘み取る",
      "高さ50cm位で先端の柔らかい茎葉から収穫",
    ],
    warnings: [],
    westNote: "そら豆の後作として同じプランターを使用。石灰水で土壌調整してからスタート。",
    photos: [
      "moroheiya_250615_1.jpg",
    ],
    timeline: [
      { date: "5/11", tags: ["grow"], title: "スナップエンドウ終了・根取り＆石灰水", text: "前作のスナップエンドウを終了し根を取り除き、石灰水で土壌調整。", photos: [] },
      { date: "5/17", tags: ["grow"], title: "元肥追加", text: "次作に向けて元肥を追加。", photos: [] },
      { date: "5/29", tags: ["seed"], title: "種まき", text: "ポットに種まき（やや適当に播種）。", photos: ["moroheiya_250529_1.jpg"] },
      { date: "6/2", tags: ["grow"], title: "双葉複数発芽・間引き", text: "双葉がいくつも発芽。3株程度に間引き。", photos: ["moroheiya_250602_1.jpg"] },
      {
        date: "6/7",
        tags: ["grow"],
        title: "赤・黒ポットそれぞれで複数株が双葉の状態",
        text: "赤ポット・黒ポットそれぞれに複数株が発芽し、双葉が開いている。",
        photos: ["moroheiya_250607_1.jpg"],
      },
      {
        date: "6/15",
        tags: ["grow"],
        title: "本葉3枚目が出始め",
        text: "赤ポット・黒ポットそれぞれに1株ずつ育苗中。本葉3枚目が展開し始めた段階。",
        photos: ["moroheiya_250615_1.jpg"],
      },
      {
        date: "6/19",
        tags: ["grow"],
        title: "本葉4枚目展開・定植実施",
        text: "本葉4枚目が出てきたタイミングで定植を実施。赤ポット・黒ポットの株をそれぞれ大きめのプランターへ植え替え。",
        photos: ["moroheiya_250619_1.jpg", "moroheiya_250619_2.jpg", "moroheiya_250619_3.jpg"],
      },
      {
        date: "7/5",
        tags: ["grow"],
        title: "徒長気味のため摘芯",
        text: "草丈20cmほどになり徒長している様子が見られたため摘芯。葉の脇についている小さな芽に期待し、梅雨明け後の生育を待つ。",
        photos: ["moroheiya_250705_1.jpg", "moroheiya_250705_2.jpg"],
      },
      {
        date: "7/12",
        tags: ["trouble", "fail"],
        title: "生育が思わしくなく失敗の可能性",
        text: "摘芯後の生育が思わしくなく、葉も萎れて変色が見られる。失敗の可能性が高い状態。",
        photos: ["moroheiya_250712_1.jpg"],
      },
      {
        date: "7/16",
        tags: ["fail"],
        title: "完全に失敗・撤去",
        text: "完全に枯れてしまい失敗と判断、撤去した。根はほとんど残っていなかった。土は湿らせて透明ビニール袋に入れ、天日で消毒して再生する予定。",
        photos: ["moroheiya_250716_1.jpg"],
      },
    ],
  },

  {
    id: "rucola",
    emoji: "🥗",
    name: "ルッコラ",
    sub: "種まきから育苗",
    color: "teal",
    status: "🏁 栽培終了（収穫完了）",
    season: "2026年春蒔き",
    westRating: 5,
    basicData: [
      { key: "分類", val: "アブラナ科" },
      { key: "空白期間（連作対策）", val: "1〜2年" },
      { key: "種子(好光or嫌光)", val: "好光" },
      { key: "種まき時期", val: "3〜5月" },
      { key: "定植時期", val: "3〜5月" },
      { key: "収穫時期", val: "4〜6月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、やや乾燥気味がOK" },
      { key: "株間目安", val: "10〜15cm" },
      { key: "推奨プランター", val: "広め：深さ20cm～、幅30cm～" },
    ],
    points: [
      "背丈10cm位から液肥を開始",
      "液肥は週1回",
    ],
    warnings: [],
    westNote: "西向きでも葉物は問題なく育つ。ルッコラは特に相性が良く、種まきから旺盛に生育している。",
    photos: [
      "rucola_250621_1.jpg",
      "rucola_250619_1.jpg",
    ],
    timeline: [
      { date: "4/29", tags: ["seed"], title: "種まき", text: "長鉢に種まき。", photos: [] },
      {
        date: "5/11",
        tags: ["grow"],
        title: "発芽・双葉が展開",
        text: "長鉢のあちこちで双葉が展開し、発芽が順調に進んでいる。",
        photos: ["rucola_250511_1.jpg"],
      },
      {
        date: "5/29",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["rucola_250529_1.jpg"],
      },
      {
        date: "6/1",
        tags: ["grow"],
        title: "本葉が密に展開・生育旺盛",
        text: "本葉が次々と展開し、プランター全体に葉が密生。順調に生育中。",
        photos: ["rucola_250601_1.jpg"],
      },
      {
        date: "6/7",
        tags: ["grow"],
        title: "液肥実施",
        text: "背丈が10cmほどになったため液肥を開始。葉が密生し旺盛に生育中。",
        photos: ["rucola_250607_1.jpg"],
      },
      {
        date: "6/15",
        tags: ["grow"],
        title: "旺盛に生育中・収穫間近",
        text: "長鉢いっぱいに葉が茂り、収穫間近の状態。",
        photos: ["rucola_250615_1.jpg"],
      },
      { date: "6/18", tags: ["harvest"], title: "収穫 4〜5株", text: "外側の株から4〜5株を収穫。", photos: [] },
      {
        date: "6/19",
        tags: ["grow"],
        title: "さらに生育・葉が密に",
        text: "6/15からさらに葉が密になり、いよいよ収穫適期。",
        photos: ["rucola_250619_1.jpg"],
      },
      { date: "6/20", tags: ["harvest"], title: "収穫 4〜5株", text: "前回に続けて4〜5株を収穫。", photos: [] },
      {
        date: "6/21",
        tags: ["grow"],
        title: "元肥入りの土を増土・追肥なし",
        text: "元肥入りの土を増土したため、追肥は実施せず。収穫後も次々と葉が展開している。",
        photos: ["rucola_250621_1.jpg"],
      },
      {
        date: "7/5",
        tags: ["trouble", "grow"],
        title: "葉に白い斑点も見られるが旺盛に生育",
        text: "一部の葉に白い斑点のようなものが見られるが、全体としては旺盛に生育を続けている。",
        photos: ["rucola_250705_1.jpg"],
      },
      {
        date: "7/12",
        tags: ["grow"],
        title: "液肥実施",
        text: "液肥を実施。",
        photos: ["rucola_250712_1.jpg"],
      },
      {
        date: "7/16",
        tags: ["harvest", "fail"],
        title: "5株ほど最終収穫・栽培終了",
        text: "5株ほどを収穫して栽培終了。土は乾かしてから根を取り除く予定。",
        photos: ["rucola_250716_1.jpg", "log_250716_soil2.jpg"],
      },
    ],
  },

  {
    id: "shungiku",
    emoji: "🌼",
    name: "春菊",
    sub: "",
    color: "moss",
    status: "🏁 栽培終了（2025年秋蒔き・4/12で終了）",
    season: "2025年秋蒔き",
    westRating: 4,
    basicData: [
      { key: "分類", val: "キク科" },
      { key: "空白期間（連作対策）", val: "1〜2年" },
      { key: "種子(好光or嫌光)", val: "好光" },
      { key: "種まき時期", val: "9〜10月" },
      { key: "定植時期", val: "9〜10月" },
      { key: "収穫時期", val: "10〜12月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、やや湿り気" },
      { key: "株間目安", val: "15〜20cm" },
      { key: "推奨プランター", val: "広め：深さ20cm～、幅30cm～" },
    ],
    points: [
      "芽が出て1〜2週間後：1回目の間引き・土寄せ（株間2〜3cm）",
      "本葉3〜4枚：2回目の間引き・土寄せ（株間5〜6cm）＆追肥。以降2週に1回追肥",
      "多肥料にするとアブラムシが発生しやすいので注意",
      "収穫の目安：草丈20〜30cm",
    ],
    warnings: [],
    westNote: "",
    photos: [],
    timeline: [
      { date: "10/7", tags: ["seed"], title: "種まき", text: "中葉しゅんぎく（株立型・摘み取り型）の種をまく。", photos: [] },
      { date: "10/10", tags: ["grow"], title: "芽が出始めた", text: "", photos: [] },
      { date: "10/16", tags: ["grow"], title: "生育中", text: "", photos: ["shungiku_251016_1.jpg"] },
      { date: "10/17", tags: ["grow"], title: "間引き", text: "", photos: [] },
      { date: "10/20", tags: ["grow"], title: "土寄せ1回目", text: "", photos: [] },
      { date: "10/28", tags: ["grow"], title: "間引き2回目・追肥", text: "2回目の間引き（株間5cm〜）と追肥（化成肥料）を実施。", photos: [] },
      { date: "11/11", tags: ["grow"], title: "石灰水で灌水", text: "", photos: [] },
      { date: "11/16", tags: ["grow"], title: "化成肥料追肥", text: "", photos: [] },
      { date: "11/18", tags: ["grow"], title: "ハイポネックスの余った水をあげる", text: "", photos: [] },
      { date: "11/28", tags: ["grow"], title: "化成肥料追肥", text: "", photos: [] },
      { date: "12/30", tags: ["harvest"], title: "2株採取", text: "", photos: [] },
      { date: "2/23", tags: ["harvest", "grow"], title: "8株分採取・追肥", text: "", photos: [] },
      { date: "3/9", tags: ["grow"], title: "追肥", text: "", photos: [] },
      { date: "3/29", tags: ["grow"], title: "追肥", text: "", photos: [] },
      { date: "4/3", tags: ["grow"], title: "液肥", text: "", photos: [] },
      { date: "4/5", tags: ["harvest", "grow"], title: "収穫・追肥", text: "", photos: [] },
      { date: "4/10", tags: ["harvest"], title: "収穫", text: "", photos: [] },
      { date: "4/12", tags: ["grow"], title: "一部を残して終了", text: "花を咲かせるため1株を移し、他は栽培終了。", photos: [] },
    ],
  },

  {
    id: "soramame",
    emoji: "🫘",
    name: "そら豆",
    sub: "",
    color: "bark",
    status: "🏁 栽培終了（5/29で終了）",
    season: "2025年秋蒔き",
    westRating: 3,
    basicData: [
      { key: "分類", val: "マメ科" },
      { key: "空白期間（連作対策）", val: "4〜5年" },
      { key: "種子(好光or嫌光)", val: "嫌光" },
      { key: "種まき時期", val: "10〜11月" },
      { key: "定植時期", val: "10〜11月" },
      { key: "収穫時期", val: "4〜5月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、やや湿り気" },
      { key: "株間目安", val: "30〜40cm" },
      { key: "推奨プランター", val: "広め：深さ20cm～、幅30cm～" },
    ],
    points: [
      "種はおはぐろを斜め下に向け、種子のお尻が地上に出るくらいの深さに植える",
      "ポットで育苗する場合は2つ植えて、本葉が展開したら1本にする",
      "育苗日数約20日で定植する",
      "冬越えは15〜20cmほどが良い",
      "12月下旬に防寒対策",
      "【追肥（化成肥料）】20cm位になる2月中旬、開花が始まったら2週に1回",
      "草丈5〜60cmで6〜7本に整枝・土寄せ",
      "背丈90〜100cmで摘芯",
      "開花後は乾燥に注意",
    ],
    warnings: [],
    westNote: "",
    photos: [],
    timeline: [
      { date: "10/7", tags: ["seed"], title: "種をポットに3つ撒く", text: "", photos: [] },
      { date: "10/11", tags: ["grow"], title: "芽が出始めた", text: "", photos: [] },
      { date: "10/16", tags: ["grow"], title: "生育中", text: "", photos: ["soramame_251016_1.jpg"] },
      { date: "10/28", tags: ["grow"], title: "定植", text: "根鉢が崩れてしまい、根を切って定植。", photos: [] },
      { date: "11/3", tags: ["grow"], title: "支柱を設置", text: "メロンに使ったツルを伝わせる支柱を挿した。", photos: [] },
      { date: "12/5", tags: ["grow"], title: "ビニールで防寒", text: "", photos: [] },
      { date: "1/16", tags: ["grow"], title: "一つを洗濯ネットに変更", text: "", photos: [] },
      { date: "1/25", tags: ["trouble"], title: "水やり不足で萎れ気味", text: "洗濯ネットの方が萎れ気味。袋の方は大丈夫。1週間以上水をあげていなかった。", photos: [] },
      { date: "2/2", tags: ["trouble"], title: "霜焼けの疑い", text: "ネットの方、寒さによる霜焼けか、葉が一部黒く変色。除去した。", photos: [] },
      { date: "2/7", tags: ["grow"], title: "再度ビニールで防寒", text: "", photos: [] },
      { date: "2/23", tags: ["trouble"], title: "枯れかけ、ビニール撤去", text: "この3日間の20℃弱の気温で2株とも水やり不足になり枯れかける。ビニールを外してネットだけにした。", photos: [] },
      { date: "3/5", tags: ["flower"], title: "花がしっかり咲き出した", text: "", photos: [] },
      { date: "3/25", tags: ["grow"], title: "実がなり出した", text: "", photos: [] },
      { date: "4/3", tags: ["grow"], title: "液肥", text: "", photos: [] },
      { date: "4/13", tags: ["grow"], title: "追肥", text: "", photos: [] },
      { date: "4/20", tags: ["grow"], title: "液肥", text: "", photos: [] },
      { date: "4/21", tags: ["grow"], title: "実が垂れ始めた", text: "", photos: [] },
      { date: "5/2", tags: ["grow"], title: "追肥", text: "", photos: [] },
      { date: "5/11", tags: ["harvest", "grow"], title: "6つ収穫・追肥", text: "6つ収穫。着果は11個。追肥も実施。", photos: [] },
      { date: "5/24", tags: ["grow"], title: "追肥", text: "", photos: [] },
      { date: "5/29", tags: ["harvest"], title: "5個収穫・栽培終了", text: "5個収穫し、今期の栽培を終了。", photos: [] },
    ],
  },

  {
    id: "snapendo",
    emoji: "🌱",
    name: "スナップエンドウ",
    sub: "",
    color: "teal",
    status: "🏁 栽培終了（5/17で終了）",
    season: "2025年秋蒔き",
    westRating: 4,
    basicData: [
      { key: "分類", val: "マメ科" },
      { key: "空白期間（連作対策）", val: "4〜5年" },
      { key: "種子(好光or嫌光)", val: "嫌光" },
      { key: "種まき時期", val: "10〜11月" },
      { key: "定植時期", val: "10〜11月" },
      { key: "収穫時期", val: "4〜6月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、やや湿り気" },
      { key: "株間目安", val: "20〜30cm" },
      { key: "推奨プランター", val: "バランス：深さ25cm～、幅30cm～" },
    ],
    points: [
      "種まき適温は18〜22℃、10月中旬以降が目安",
      "根は直根性",
      "冬越えは15〜20cmほどが良い",
      "追肥は花が咲いて実がつき始めたら1回、その後は1ヶ月毎に様子を見ながら",
      "着莢肥大期に追肥する際は中耕・除草・土寄せも合わせて行う",
      "2mくらい伸びて孫づるが出てきたあたりで摘心",
      "【肥料】元肥で1回、花が咲いて実がつき始めたら1回",
    ],
    warnings: [],
    westNote: "",
    photos: [],
    timeline: [
      { date: "10/7", tags: ["seed"], title: "種まき（3つずつ4ポット）", text: "", photos: [] },
      { date: "10/11", tags: ["grow"], title: "1つ目の芽が出始めた", text: "", photos: [] },
      { date: "10/14", tags: ["grow"], title: "全ポットで発芽", text: "", photos: [] },
      { date: "10/16", tags: ["grow"], title: "早くも10cm越え", text: "生育が早く、既に10cmを超えている様子。", photos: ["snapendo_251016_1.jpg"] },
      { date: "10/20", tags: ["grow"], title: "2ポット刈って再度種まき・2ポット定植", text: "2ポット分を刈り取り、再度2粒ずつ種まき。同時に2ポットを定植。", photos: [] },
      { date: "10/28", tags: ["grow"], title: "2ポット発芽し始め", text: "", photos: [] },
      { date: "11/16", tags: ["grow"], title: "2ポット定植", text: "", photos: [] },
      { date: "12/5", tags: ["grow"], title: "土上を防寒", text: "", photos: [] },
      { date: "12/30", tags: ["flower"], title: "花が咲き始めた", text: "", photos: [] },
      { date: "2/9", tags: ["grow"], title: "実がなり始めた", text: "", photos: [] },
      { date: "2/23", tags: ["grow"], title: "追肥", text: "", photos: [] },
      { date: "2/26", tags: ["grow"], title: "一番高い株を摘心", text: "", photos: [] },
      { date: "3/19", tags: ["harvest"], title: "初収穫（3つ）", text: "", photos: [] },
      { date: "4/3", tags: ["grow"], title: "液肥", text: "", photos: [] },
      { date: "4/5", tags: ["trouble", "grow"], title: "合計21個ほど着果・うどんこ病の疑い", text: "合計21個ほど実がなっている。うどんこ病の疑いがあり、アーリーセーフを週1回くらいのペースで散布。", photos: [] },
      { date: "4/13", tags: ["harvest", "grow"], title: "28個収穫・追肥", text: "", photos: [] },
      { date: "4/20", tags: ["harvest", "grow"], title: "31個収穫・追肥", text: "", photos: [] },
      { date: "5/2", tags: ["grow"], title: "追肥", text: "", photos: [] },
      { date: "5/11", tags: ["harvest"], title: "1つの鉢を終了・片付け", text: "", photos: [] },
      { date: "5/15", tags: ["harvest"], title: "25個収穫（累計87個）", text: "", photos: [] },
      { date: "5/17", tags: ["harvest"], title: "2つ目の鉢も片付け終了", text: "今期の栽培を終了。", photos: [] },
    ],
  },

  {
    id: "sanchu",
    emoji: "🥬",
    name: "サンチュ",
    sub: "水耕栽培",
    color: "amber",
    status: "🏁 栽培終了（5/20で終了）",
    season: "2025年秋蒔き",
    westRating: 4,
    basicData: [
      { key: "分類", val: "キク科（水耕栽培）" },
      { key: "空白期間（連作対策）", val: "水耕栽培のため対象外" },
      { key: "種子(好光or嫌光)", val: "―" },
      { key: "種まき時期", val: "10月頃（水に浸したスポンジへ）" },
      { key: "定植時期", val: "水耕のため定植なし" },
      { key: "収穫時期", val: "11〜5月（とう立ちまで随時収穫）" },
      { key: "最適な土の性質", val: "―（培養液のECで管理）" },
      { key: "株間目安", val: "水耕栽培のため対象外" },
      { key: "推奨プランター", val: "水耕栽培キット（スポンジ＋培養液）" },
    ],
    points: [
      "EC 800〜1200で管理",
      "暖かい時期は高め、寒い時期は低めに調整",
      "1.5週に1回、2Lに1.5gを2つ、水耕液を交換",
      "水が少なくなっていたら水を足す程度でOK",
    ],
    warnings: [],
    westNote: "",
    photos: [],
    timeline: [
      { date: "10/3夜", tags: ["seed"], title: "スポンジへ種まき", text: "水耕栽培のため、スポンジに種をまく。", photos: [] },
      { date: "10/5", tags: ["grow"], title: "芽が出だした", text: "", photos: [] },
      { date: "10/7", tags: ["grow"], title: "双葉が開くものも", text: "", photos: [] },
      { date: "10/12", tags: ["grow"], title: "水耕開始（EC900ちょっと）", text: "", photos: ["sanchu_251012_1.jpg"] },
      { date: "10/19", tags: ["grow"], title: "EC1400", text: "", photos: [] },
      { date: "10/27", tags: ["trouble", "grow"], title: "EC900（2Lに1g）・葉の周囲が透明に", text: "葉の周囲が透明になる症状。日照不足か急な寒さのせいか。11/1に回復（5日後EC810に）。", photos: [] },
      { date: "11/1", tags: ["grow"], title: "EC1130→EC830", text: "4日後に水を足してEC830へ。", photos: [] },
      { date: "11/9", tags: ["grow"], title: "EC1030→忘れ", text: "13日に余っていた溶液を足す予定が忘れてしまった。", photos: [] },
      { date: "11/18", tags: ["grow"], title: "EC1180→1030", text: "", photos: [] },
      { date: "11/22", tags: ["harvest", "trouble"], title: "18枚収穫・薄っぺらい", text: "18枚収穫。その週は室内にほぼ置いていたため、食べた感じが薄っぺらい。日光が必要と実感。", photos: [] },
      { date: "11/24", tags: ["grow"], title: "EC1180・屋外へ", text: "", photos: [] },
      { date: "11/30", tags: ["grow"], title: "EC1020→750", text: "ベランダの方がよく伸びている感じがある。", photos: [] },
      { date: "12/7", tags: ["grow"], title: "EC1050→720・簡易温室化", text: "120Lの袋を被せて温室のようにした。", photos: [] },
      { date: "12/9", tags: ["harvest"], title: "24枚収穫", text: "", photos: [] },
      { date: "12/14", tags: ["grow"], title: "EC1120", text: "", photos: [] },
      { date: "12/21", tags: ["grow"], title: "EC1050→700", text: "", photos: [] },
      { date: "12/25", tags: ["harvest"], title: "12枚収穫", text: "", photos: [] },
      { date: "12/28", tags: ["grow"], title: "EC1000", text: "", photos: [] },
      { date: "1/8", tags: ["grow"], title: "EC830→800", text: "", photos: [] },
      { date: "1/11", tags: ["harvest"], title: "5枚収穫", text: "", photos: [] },
      { date: "1/12", tags: ["harvest"], title: "6枚収穫", text: "", photos: [] },
      { date: "1/18", tags: ["grow"], title: "EC1000→700", text: "", photos: [] },
      { date: "1/25", tags: ["grow"], title: "水を追加", text: "", photos: [] },
      { date: "1/29", tags: ["grow"], title: "EC900→900", text: "", photos: [] },
      { date: "2/8", tags: ["harvest"], title: "25枚収穫", text: "EC900。", photos: [] },
      { date: "2/23", tags: ["harvest"], title: "22枚収穫", text: "", photos: [] },
      { date: "3/5", tags: ["harvest", "grow"], title: "24枚収穫・水継ぎ足し", text: "", photos: [] },
      { date: "3/15", tags: ["harvest"], title: "16枚収穫", text: "日当たりが良くなったからか葉が厚い。", photos: [] },
      { date: "3/28", tags: ["harvest"], title: "6枚収穫", text: "〜27日までで6枚収穫。", photos: [] },
      { date: "4/5", tags: ["harvest"], title: "21枚収穫", text: "", photos: [] },
      { date: "4/10", tags: ["harvest"], title: "21枚収穫", text: "", photos: [] },
      { date: "4/19", tags: ["harvest"], title: "30枚以上収穫", text: "", photos: [] },
      { date: "4/28", tags: ["harvest"], title: "31枚収穫", text: "", photos: [] },
      { date: "5/7", tags: ["harvest"], title: "33枚収穫", text: "", photos: [] },
      { date: "5/20", tags: ["harvest"], title: "40枚近く収穫・栽培終了", text: "とう立ちし始めたため終了。やや葉は硬めで青臭さもあったが、サラダで食べた。", photos: [] },
    ],
  },

  {
    id: "rucola-aki",
    emoji: "🥗",
    name: "ルッコラ（2025年秋蒔き）",
    sub: "種まきから育苗",
    color: "teal",
    status: "🏁 栽培終了（4/18で終了）",
    season: "2025年秋蒔き",
    westRating: 4,
    basicData: [
      { key: "分類", val: "アブラナ科" },
      { key: "空白期間（連作対策）", val: "1〜2年" },
      { key: "種子(好光or嫌光)", val: "好光" },
      { key: "種まき時期", val: "3〜5月" },
      { key: "定植時期", val: "3〜5月" },
      { key: "収穫時期", val: "4〜6月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、やや乾燥気味がOK" },
      { key: "株間目安", val: "10〜15cm" },
      { key: "推奨プランター", val: "広め：深さ20cm～、幅30cm～" },
    ],
    points: [
      "背丈10cm位から液肥を開始",
      "液肥は週1回",
    ],
    warnings: [],
    westNote: "",
    photos: [],
    timeline: [
      { date: "10/5", tags: ["seed"], title: "種まき", text: "", photos: [] },
      { date: "10/9", tags: ["grow"], title: "芽が出始めた", text: "", photos: [] },
      { date: "10/16", tags: ["grow"], title: "生育中", text: "", photos: ["rucola_251016_1.jpg"] },
      { date: "10/17", tags: ["grow"], title: "間引き", text: "", photos: [] },
      { date: "12/25", tags: ["harvest"], title: "12株位収穫", text: "", photos: [] },
      { date: "2/2", tags: ["harvest"], title: "計5株くらい収穫", text: "", photos: [] },
      { date: "2/23", tags: ["harvest"], title: "2株収穫", text: "", photos: [] },
      { date: "3/5", tags: ["seed"], title: "種まき（2回目）", text: "", photos: [] },
      { date: "3/13", tags: ["grow"], title: "芽が出始め", text: "", photos: [] },
      { date: "3/19", tags: ["seed"], title: "種まき（3回目）", text: "", photos: [] },
      { date: "4/18", tags: ["trouble", "fail"], title: "シソが大量発生し終了", text: "紫蘇の実生が大量発生（連作でない場所で発生しやすい？午前の日当たりが良いと生えるのかもしれない）。今期の栽培を終了。", photos: [] },
    ],
  },

  {
    id: "chili",
    emoji: "🌶️",
    name: "唐辛子",
    sub: "",
    color: "amber",
    status: "🌶️ 結実中",
    season: "2026年春蒔き",
    westRating: 3,
    basicData: [
      { key: "分類", val: "ナス科" },
      { key: "空白期間（連作対策）", val: "3〜4年" },
      { key: "種子(好光or嫌光)", val: "嫌光" },
      { key: "種まき時期", val: "5～6月" },
      { key: "定植時期", val: "4〜5月" },
      { key: "収穫時期", val: "7〜10月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、水はけよく乾燥気味" },
      { key: "株間目安", val: "30〜40cm" },
      { key: "推奨プランター", val: "バランス：深さ25cm～、幅30cm～" },
    ],
    points: [
      "過湿・乾燥しすぎのどちらもNG",
      "定植後3週間、または一番花がついたタイミングで追肥開始",
      "化成肥料は3週に1回",
      "液肥は週1回",
      "倒れないよう支柱を立てる",
      "一番花がついたら、その下の枝までのわき芽をすべて摘み取る（花はそのまま残す）",
      "3本仕立てにする",
    ],
    warnings: [],
    westNote: "西向きでも開花・着果まで順調に進んでいる。支柱でしっかり支えながら経過観察中。",
    photos: [
      "chili_250615_1.jpg",
      "chili_250615_2.jpg",
    ],
    timeline: [
      { date: "4/29", tags: ["grow"], title: "購入・植え替え", text: "苗を購入し、プランターへ植え替え。", photos: ["chili_250429_1.jpg"] },
      { date: "5/29", tags: ["flower"], title: "白い花が開花・化成肥料", text: "白い花が咲き始めた。化成肥料を施用。", photos: ["chili_250529_1.jpg"] },
      { date: "6/1", tags: ["flower", "grow"], title: "一番花が着花・わき芽かき", text: "一番花が付いたタイミングでわき芽かきを実施。その下の枝までのわき芽を摘み取り、3本仕立てに整える。", photos: ["chili_250601_1.jpg"] },
      { date: "6/5", tags: ["grow"], title: "実が着き始める", text: "小さな実が着き始めた。", photos: [] },
      {
        date: "6/7",
        tags: ["flower", "grow"],
        title: "複数の花が開花・実も成長中",
        text: "白い花が複数咲いており、小さな実もいくつか確認できる。株全体も大きく茂ってきた。",
        photos: ["chili_250607_2.jpg", "chili_250607_1.jpg"],
      },
      {
        date: "6/15",
        tags: ["flower"],
        title: "開花・小さな実が確認できる",
        text: "白い花が複数咲いており、小さな緑の実も確認できる。青い支柱ケージで茎をしっかり支えている。",
        photos: [
          "chili_250615_1.jpg",
          "chili_250615_2.jpg",
        ],
      },
      {
        date: "6/19",
        tags: ["grow"],
        title: "化成肥料・内側の2枝を剪定",
        text: "頂部の内側に込み入って伸びた2本の枝を剪定して風通しと光を改善。化成肥料を追肥。剪定した枝には白い花と小さな実がついていた。",
        photos: [
          "chili_250619_3.jpg",
          "chili_250619_1.jpg",
          "chili_250619_2.jpg",
        ],
      },
      {
        date: "7/5",
        tags: ["grow"],
        title: "わき芽が次々発生・わき芽かき実施",
        text: "わき芽が次々と出てきているためわき芽かきを実施。実も複数着果中。",
        photos: ["chili_250705_1.jpg", "chili_250705_2.jpg"],
      },
      {
        date: "7/7",
        tags: ["grow"],
        title: "わき芽が大量発生・わき芽かき実施",
        text: "わき芽が大量に出てきたため、再びわき芽かきを実施。実も順調に育っている。",
        photos: ["chili_250707_1.jpg", "chili_250707_2.jpg"],
      },
      {
        date: "7/12",
        tags: ["grow", "harvest"],
        title: "わき芽かき実施・実が色づき始め",
        text: "再度わき芽かきを実施。実の一部が赤く色づき始め、収穫が近づいている。",
        photos: ["chili_250712_1.jpg", "chili_250712_2.jpg"],
      },
      {
        date: "7/19",
        tags: ["harvest"],
        title: "2個初収穫（今期累計2個）",
        text: "赤く色づいた実を2個初収穫。今期の収穫累計は2個。",
        photos: ["chili_250719_1.jpg", "chili_250719_2.jpg", "chili_250719_3.jpg"],
      },
      {
        date: "7/23",
        tags: ["trouble"],
        title: "猛暑で水切れ・萎れ",
        text: "7/21夜の水やりを最後に泊まりで不在。最高気温37℃・36℃の猛暑が続き、10時頃帰宅時には萎れていた。他の植物では、ミニトマトの土がカラカラだったが萎れは見られず。生育があまり良くない他の株の土は湿った状態だった。",
        photos: ["chili_250723_1.jpg"],
      },
      {
        date: "7/24",
        tags: ["harvest"],
        title: "3個収穫（今期累計5個）",
        text: "赤く色づいた実を3個収穫。今期の収穫累計は5個。",
        photos: ["chili_250724_1.jpg"],
      },
      {
        date: "7/27",
        tags: ["grow"],
        title: "水切れから回復・複数着果",
        text: "水切れから回復し、実が複数着果している。",
        photos: ["chili_250727_1.jpg", "chili_250727_2.jpg"],
      },
      {
        date: "8/2",
        tags: ["harvest", "grow"],
        title: "5個収穫（今期累計10個）・化成肥料追肥",
        text: "5個収穫。今期の収穫累計は10個。前回収穫して乾燥させた実と並べて撮影。化成肥料の追肥も実施。",
        photos: ["chili_250802_1.jpg", "chili_250802_2.jpg", "chili_250802_3.jpg", "chili_250802_4.jpg"],
      },
      {
        date: "8/8",
        tags: ["grow"],
        title: "頂部が茂り葉色が深緑に変化",
        text: "頂部が鬱蒼と茂り、葉の色が黄緑から深緑へと変化してきた。",
        photos: ["chili_250808_1.jpg", "chili_250808_2.jpg"],
      },
      {
        date: "8/16",
        tags: ["grow"],
        title: "3本仕立てに剪定",
        text: "3本仕立てになるよう剪定を実施。",
        photos: [],
      },
      {
        date: "8/23",
        tags: ["trouble"],
        title: "着花しても結実せず落下",
        text: "花はついたものの実にならず落ちてしまった。日照不足か肥料の問題か、原因は不明。",
        photos: ["chili_260823_1.jpg"],
      },
      {
        date: "8/28",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。",
        photos: [],
      },
      {
        date: "8/30",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["chili_260830_1.jpg"],
      },
      {
        date: "9/5",
        tags: ["grow"],
        title: "液肥施行・新しい芽が再度出始め",
        text: "液肥を施行。新しい芽が再度出始めてきた。（※直近の天候は全体ログ参照）",
        photos: ["chili_260905_1.jpg"],
      },
      {
        date: "9/11",
        tags: ["grow"],
        title: "新芽多数・下部の脇芽を除去し上部は残す・化成肥料施行",
        text: "新しい芽がたくさん出てきた。下部の脇芽は摘み取り、上部の芽は残してみることにした。化成肥料を施行。（※直近の天候は全体ログ参照）",
        photos: ["chili_260911_1.jpg"],
      },
    ],
  },

  {
    id: "nira",
    emoji: "🌿",
    name: "ニラ",
    sub: "種まきから育苗中",
    color: "olive",
    status: "🌱 栽培中",
    season: "2026年春蒔き",
    westRating: 4,
    basicData: [
      { key: "分類", val: "ヒガンバナ科" },
      { key: "空白期間（連作対策）", val: "1〜2年" },
      { key: "種子(好光or嫌光)", val: "嫌光" },
      { key: "種まき時期", val: "3〜5月" },
      { key: "定植時期", val: "4〜5月" },
      { key: "収穫時期", val: "収穫は翌年以降が中心" },
      { key: "最適な土の性質", val: "弱酸性〜中性、やや湿り気・有機質ないと伸びが悪い" },
      { key: "株間目安", val: "10〜15cm（密植可能）" },
      { key: "推奨プランター", val: "広め：深さ20cm～、幅30cm～" },
    ],
    points: [
      "発芽適温は18〜22℃",
      "草丈5cmで1回目の間引き（1cmずつ）",
      "草丈10cmで2回目の間引き（3〜5束を株間8cmずつに）",
      "草丈15cmまでは薄めの液肥を月1回程度",
      "草丈15cmで5束前後にまとめて株間8cmくらいに間引く",
      "草丈20〜25cmで根元から4cm残して収穫（1年目は刈り取らない育て方もある。花茎が出たら切り取る）",
      "刈り取り後は液肥を施す",
      "植え付け前に苗は半分に切り揃える",
      "できれば成長点を埋めないように土寄せする",
      "9月の化成肥料がメインの追肥",
      "冬になって葉が枯れてきたら地上部の葉茎を刈り取って冬越しさせる",
      "【2年目以降】草丈20〜25cmになったら地上部2〜3cm残して刈り取り収穫",
      "収穫後は追肥して中耕する",
    ],
    warnings: [
      "5cmや10cmでの間引きタイミングを忘れずに",
    ],
    westNote: "種まきから育苗中。西向きでも育てやすい野菜のひとつ。6月下旬の植え付けを目標に管理中。",
    photos: [
      "nira_250621_1.jpg",
      "nira_250615_1.jpg",
    ],
    timeline: [
      { date: "4/29", tags: ["seed"], title: "種まき", text: "発芽適温18〜22℃を目安に種まき。", photos: ["nira_250429_1.jpg"] },
      {
        date: "5/11",
        tags: ["grow"],
        title: "発芽・生育中",
        text: "細い芽が長鉢いっぱいに発芽し、順調に生育中。",
        photos: ["nira_250511_1.jpg"],
      },
      {
        date: "5/17",
        tags: ["grow"],
        title: "草丈6〜7cm・間引き実施",
        text: "草丈6〜7cmに成長。本来は15cmまで待つところ忘れてしまい、株間1cmと4〜5株の8cmに間引き。次回は手順通りに。",
        photos: [],
      },
      {
        date: "5/29",
        tags: ["grow"],
        title: "生育中",
        text: "細い葉が伸びてきており、順調に生育中。",
        photos: ["nira_250529_1.jpg"],
      },
      {
        date: "6/7",
        tags: ["grow"],
        title: "葉が伸びて密集",
        text: "細い葉がさらに伸びて密集してきた。",
        photos: ["nira_250607_1.jpg"],
      },
      { date: "6/11", tags: ["grow"], title: "化成肥料", text: "化成肥料を施用。", photos: [] },
      {
        date: "6/15",
        tags: ["grow"],
        title: "生育中・白長鉢でビニールハウス内管理",
        text: "白い長鉢いっぱいに細い葉が密生している。ビニールハウス内で管理中。黄色粘着トラップで害虫対策も実施。",
        photos: ["nira_250615_1.jpg"],
      },
      {
        date: "6/21",
        tags: ["grow"],
        title: "さらに伸びる",
        text: "葉が長く伸びてきた。植え付け適期の目安（草丈20cm）が近づいている。",
        photos: ["nira_250621_1.jpg"],
      },
      {
        date: "7/5",
        tags: ["grow"],
        title: "順調に生育中",
        text: "細長い葉がしっかりと伸び、順調に生育を続けている。",
        photos: ["nira_250705_1.jpg"],
      },
      {
        date: "7/12",
        tags: ["grow"],
        title: "化成肥料施行",
        text: "化成肥料を施行。",
        photos: [],
      },
      {
        date: "7/19",
        tags: ["trouble"],
        title: "大きくならず枯れ込みが見られる",
        text: "葉先が黄色く枯れ込み、大きく育たない状態。肥料切れや株の消耗、高温多湿による蒸れなどが考えられる。しばらく収穫を控えて休ませつつ、追肥で様子を見る。",
        photos: ["nira_250719_1.jpg"],
      },
      {
        date: "7/27",
        tags: ["trouble"],
        title: "枯れ込みが継続",
        text: "葉先の枯れ込みが継続している状態。",
        photos: ["nira_250727_1.jpg"],
      },
      {
        date: "8/2",
        tags: ["trouble"],
        title: "枯れ込みが継続",
        text: "",
        photos: ["nira_250802_1.jpg"],
      },
      {
        date: "8/8",
        tags: ["grow"],
        title: "水やり不足が原因？液肥施行で緑が回復",
        text: "枯れそうだったのは水やり不足が原因だった可能性。土が乾く前に毎日夕方水やりをしていたら緑色が戻ってきた。液肥を施行。",
        photos: ["nira_250808_1.jpg"],
      },
      {
        date: "8/16",
        tags: ["grow"],
        title: "よく伸びてきた・化成肥料施行",
        text: "よく伸びてきた。化成肥料を施行。",
        photos: ["nira_260816_1.jpg"],
      },
      {
        date: "8/23",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["nira_260823_1.jpg"],
      },
      {
        date: "8/28",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。",
        photos: [],
      },
      {
        date: "8/30",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["nira_260830_1.jpg"],
      },
      {
        date: "8/31",
        tags: ["harvest", "grow"],
        title: "収穫・レバニラに使用・翌日8株に間引き",
        text: "4cm以上を残して収穫。レバニラに使用した。翌日、株を前4後4の8株へ間引きを実施（間引き後の写真はなし）。",
        photos: ["nira_260831_1.jpg", "nira_260831_2.jpg"],
      },
      {
        date: "9/5",
        tags: ["grow"],
        title: "液肥施行・よく伸びている",
        text: "液肥を施行。よく伸びている。（※直近の天候は全体ログ参照）",
        photos: ["nira_260905_1.jpg"],
      },
      {
        date: "9/11",
        tags: ["grow"],
        title: "太さはないが伸びている",
        text: "太さはあまりないが、伸びている。（※直近の天候は全体ログ参照）",
        photos: ["nira_260911_1.jpg"],
      },
    ],
  },

  {
    id: "basil",
    emoji: "🌱",
    name: "バジル",
    sub: "種まきから育苗",
    color: "moss",
    status: "🏁 栽培終了（9/15で終了）",
    season: "2026年春蒔き",
    westRating: 3,
    basicData: [
      { key: "分類", val: "シソ科" },
      { key: "空白期間（連作対策）", val: "1〜2年" },
      { key: "種子(好光or嫌光)", val: "好光" },
      { key: "種まき時期", val: "4〜6月" },
      { key: "定植時期", val: "5〜6月" },
      { key: "収穫時期", val: "5〜11月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、水はけよく乾燥を嫌わない" },
      { key: "株間目安", val: "20〜30cm" },
      { key: "推奨プランター", val: "広め：深さ20cm～、幅30cm～" },
    ],
    points: [
      "【間引き】本葉2枚で株間5cmに間引き",
      "本葉4〜6枚で株間20〜30cmに最終間引き",
      "できるだけ明るい場所に置くと徒長しにくい",
      "【追肥】定植後3週以降（元肥がある場合はその効果が切れる時期の目安で調整）",
      "液肥（窒素多め）を週1回",
      "化成肥料は3週毎",
      "摘芯後に側枝が出てきたタイミングでの追肥が特に効果的",
      "【摘芯】草丈20〜25cmで先端の芽を2〜3節分摘む",
      "摘芯後に出た脇芽が15〜20cmになったら再度摘芯",
      "秋まで収穫可能",
      "花が咲くと葉の風味が落ち、その後株全体が老化するので早めに摘み取る",
    ],
    warnings: [],
    westNote: "西向きでも育つが徒長しやすいため、できるだけ高い位置に置いて西日を確保する。",
    photos: [
      "basil_250621_2.jpg",
      "basil_250621_1.jpg",
    ],
    timeline: [
      { date: "4/23", tags: ["seed"], title: "プリンカップに遮光して種まき", text: "小さなプリンカップに種をまき、遮光して発芽を促す。", photos: ["basil_250423_1.jpg"] },
      { date: "4/29", tags: ["grow"], title: "発芽確認", text: "種まきから約6日で芽が出始めた。", photos: [] },
      { date: "5/3頃", tags: ["grow"], title: "鉢まきの芽も発生・プリンカップ分を廃止", text: "別に鉢へ直まきした分も発芽。プリンカップより生育が良かったため、鉢まきの苗に絞ることに。", photos: [] },
      { date: "5/11", tags: ["grow"], title: "間引き", text: "生育の悪い苗を間引き。", photos: ["basil_250511_1.jpg"] },
      {
        date: "5/29",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["basil_250529_1.jpg"],
      },
      { date: "5/31", tags: ["grow"], title: "本葉4枚・2株に最終間引き", text: "本葉4枚に成長したタイミングで2株に最終間引き。株間を広げて生育スペースを確保。", photos: [] },
      {
        date: "6/1",
        tags: ["grow"],
        title: "双葉・本葉が展開",
        text: "プランターのあちこちで双葉や本葉が展開し、順調に育苗中。",
        photos: ["basil_250601_1.jpg"],
      },
      {
        date: "6/7",
        tags: ["grow"],
        title: "順調に生育中",
        text: "長鉢・テラコッタ鉢それぞれで本葉がしっかり展開し、順調に生育中。",
        photos: ["basil_250607_1.jpg", "basil_250607_2.jpg"],
      },
      {
        date: "6/15",
        tags: ["grow"],
        title: "生育中・テラコッタ鉢＋長鉢に複数株",
        text: "テラコッタ鉢に1株、長鉢に2株を栽培中。いずれも本葉が展開し順調に生育している。",
        photos: ["basil_250615_1.jpg"],
      },
      {
        date: "6/21",
        tags: ["grow"],
        title: "草丈8cmほどに成長",
        text: "各株とも草丈8cmほどに成長。葉の枚数も増え、順調に生育中。",
        photos: ["basil_250621_1.jpg", "basil_250621_2.jpg"],
      },
      {
        date: "7/5",
        tags: ["grow"],
        title: "最大15cmほどに成長",
        text: "最大で草丈15cmほどに成長。20〜25cmになったタイミングで先端の芽を2〜3節分摘む予定。",
        photos: ["basil_250705_1.jpg", "basil_250705_2.jpg"],
      },
      {
        date: "7/12",
        tags: ["grow", "trouble"],
        title: "1本摘芯・液肥実施・葉ダニ発生で葉水",
        text: "1本を摘芯し、液肥を実施。葉の裏にハダニの発生を確認したため葉水で対処。",
        photos: ["basil_250712_1.jpg", "basil_250712_2.jpg"],
      },
      {
        date: "7/19",
        tags: ["grow"],
        title: "液肥実施・他2株も摘芯",
        text: "液肥を実施。残る2株も摘芯を行った。",
        photos: ["basil_250719_1.jpg", "basil_250719_2.jpg"],
      },
      {
        date: "7/20",
        tags: ["trouble", "harvest"],
        title: "風通し改善のため剪定・収穫、今年は生育がやや小ぶり",
        text: "風通しを良くするため剪定を兼ねて収穫。今年は例年ほど大きく育っておらず、土の影響が疑われる（連作の影響や梅雨長引きによる日照不足も一因の可能性）。",
        photos: ["basil_250720_1.jpg", "basil_250720_2.jpg"],
      },
      {
        date: "7/27",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["basil_250727_1.jpg", "basil_250727_2.jpg"],
      },
      {
        date: "8/2",
        tags: ["harvest", "grow"],
        title: "収穫できそう・液肥実施",
        text: "収穫できそうな状態まで生育。液肥を実施。",
        photos: ["basil_250802_1.jpg", "basil_250802_2.jpg"],
      },
      {
        date: "8/6",
        tags: ["harvest"],
        title: "収穫・一部をカプレーゼに",
        text: "収穫。収穫した一部をトマト・モッツァレラと合わせてカプレーゼにした。",
        photos: ["basil_250806_1.jpg", "basil_250806_2.jpg"],
      },
      {
        date: "8/7",
        tags: ["harvest"],
        title: "収穫",
        text: "収穫。",
        photos: ["basil_250807_1.jpg"],
      },
      {
        date: "8/8",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。",
        photos: ["basil_250808_1.jpg", "basil_250808_2.jpg"],
      },
      {
        date: "8/16",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。",
        photos: ["basil_260816_1.jpg", "basil_260816_2.jpg"],
      },
      {
        date: "8/23",
        tags: ["harvest"],
        title: "収穫",
        text: "収穫。",
        photos: ["basil_260823_1.jpg", "basil_260823_2.jpg", "basil_260823_3.jpg"],
      },
      {
        date: "8/28",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。",
        photos: [],
      },
      {
        date: "8/30",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["basil_260830_1.jpg", "basil_260830_2.jpg"],
      },
      {
        date: "9/5",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。（※直近の天候は全体ログ参照）",
        photos: ["basil_260905_1.jpg", "basil_260905_2.jpg"],
      },
      {
        date: "9/11",
        tags: ["grow"],
        title: "そろそろ終了を検討中",
        text: "そろそろ栽培終了にするか検討中。種は確保済みのため、無理に育て続ける必要はない。",
        photos: ["basil_260911_1.jpg", "basil_260911_2.jpg"],
      },
      {
        date: "9/15",
        tags: ["end"],
        title: "今期栽培終了（四角プランター）",
        text: "四角プランターでの栽培を終了。種は確保済み。",
        photos: [],
      },
    ],
  },

  {
    id: "shiso",
    emoji: "🌿",
    name: "紫蘇",
    sub: "零れ種でスタート",
    color: "teal",
    status: "🌱 栽培中",
    season: "2026年春蒔き",
    westRating: 4,
    basicData: [
      { key: "分類", val: "シソ科" },
      { key: "空白期間（連作対策）", val: "1〜2年" },
      { key: "種子(好光or嫌光)", val: "好光" },
      { key: "種まき時期", val: "4〜6月" },
      { key: "定植時期", val: "5〜6月" },
      { key: "収穫時期", val: "6〜10月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、有機質少し多め" },
      { key: "株間目安", val: "20〜30cm" },
      { key: "推奨プランター", val: "広め：深さ20cm～、幅30cm～" },
    ],
    points: [
      "本葉8枚で追肥開始（以降は固形肥料か液肥を月1〜2回）",
      "夏の強い日差しの時期は寒冷紗で保護",
      "収穫は葉が10枚以上になってから、下の方の葉から",
      "収穫を始めたら1ヶ月に1〜2回、10g程度の追肥",
      "高さ30cm位で摘心",
    ],
    warnings: [],
    westNote: "零れ種から自然発芽した株。西向きでも旺盛に生育中。摘芯を繰り返してわき芽を増やす管理を継続。",
    photos: [
      "shiso_250619_2.jpg",
      "shiso_250619_1.jpg",
    ],
    timeline: [
      {
        date: "零れ種",
        tags: ["seed"],
        title: "零れ種から自然発芽",
        text: "昨年の株からこぼれた種が自然に発芽。植え替えて栽培開始。",
        photos: [],
      },
      {
        date: "5/29",
        tags: ["grow"],
        title: "液肥実施",
        text: "初回の液肥を実施。",
        photos: ["shiso_250529_1.jpg"],
      },
      {
        date: "6/1",
        tags: ["grow"],
        title: "摘芯（1株）・ボカシ肥料投入",
        text: "1株を摘芯。コーヒーかすのボカシ肥料を1株に大さじ1杯ほど投入。",
        photos: ["shiso_250601_1.jpg"],
      },
      {
        date: "6/3",
        tags: ["harvest"],
        title: "初収穫 5枚",
        text: "下葉から5枚収穫。",
        photos: [],
      },
      {
        date: "6/5",
        tags: ["grow"],
        title: "液肥実施",
        text: "液肥を実施。",
        photos: [],
      },
      {
        date: "6/7",
        tags: ["grow"],
        title: "生育中",
        text: "四角い茶色プランターの株、白い鉢の株ともに葉を大きく広げ、旺盛に生育中。",
        photos: ["shiso_250607_2.jpg", "shiso_250607_1.jpg"],
      },
      {
        date: "6/12",
        tags: ["grow"],
        title: "液肥実施",
        text: "液肥を実施。",
        photos: [],
      },
      {
        date: "6/15",
        tags: ["grow"],
        title: "摘芯実施・草丈30cm（左株）",
        text: "四角い鉢の左株が草丈約30cmになったため摘芯。右株は先に摘芯済み。",
        photos: [
          "shiso_250615_2.jpg",
          "shiso_250615_1.jpg",
        ],
      },
      {
        date: "6/19",
        tags: ["grow"],
        title: "液肥実施・丸鉢株も摘芯",
        text: "液肥を実施（週1回ペースで継続予定）。丸い鉢の株も草丈30cmほどになったため摘芯。",
        photos: [
          "shiso_250619_2.jpg",
          "shiso_250619_1.jpg",
        ],
      },
      {
        date: "6/21",
        tags: ["harvest"],
        title: "少し収穫",
        text: "少し収穫。冷やし中華の具に使用。",
        photos: ["shiso_250621_1.jpg"],
      },
      {
        date: "6/28",
        tags: ["grow"],
        title: "化成肥料追肥",
        text: "化成肥料を追肥。葉が大きく茂り旺盛な生育。",
        photos: ["shiso_250628_1.jpg"],
      },
      {
        date: "6/30",
        tags: ["trouble"],
        title: "1株で葉が萎れ・変色（肥料焼けの疑い）",
        text: "1株で葉がしおれて落ちたり、葉の周囲が黒く変色している箇所を確認。6/28の追肥による肥料焼けの可能性がある。他の株への影響も含め経過観察中。",
        photos: ["shiso_250630_1.jpg", "shiso_250630_2.jpg"],
      },
      {
        date: "7/2",
        tags: ["trouble"],
        title: "3株の明暗が分かれる（1株完全にダメ・1株葉焼け・1株無事）",
        text: "肥料焼けの経過観察の結果、1株は完全に枯れてしまい終了。もう1株は葉焼けの症状が残るが持ち直しつつある。残り1株は目立った症状がなく無事。肥料焼け対策として、鉢の縁ギリギリまで水を注いで土中の余分な肥料分を洗い流す処置を2〜3回実施した。",
        photos: ["shiso_250702_1.jpg", "shiso_250702_2.jpg", "shiso_250702_3.jpg"],
      },
      {
        date: "7/12",
        tags: ["grow"],
        title: "生育中",
        text: "葉が大きく茂り、順調に生育中。",
        photos: ["shiso_250712_1.jpg"],
      },
      {
        date: "7/15",
        tags: ["trouble", "harvest"],
        title: "ハダニ被害多め・葉水と剪定・収穫",
        text: "特にハダニの被害が目立ち、全体に葉水を実施。被害の大きい葉を剪定し、収穫も兼ねて実施。",
        photos: ["shiso_250715_1.jpg", "shiso_250715_2.jpg", "shiso_250715_3.jpg"],
      },
      {
        date: "7/19",
        tags: ["trouble", "grow"],
        title: "液肥実施・葉の色が薄い",
        text: "液肥を実施。葉の色がやや薄くなってきている印象で、経過観察中。",
        photos: ["shiso_250719_1.jpg", "shiso_250719_2.jpg"],
      },
      {
        date: "7/27",
        tags: ["trouble"],
        title: "ハダニ出現・状態の悪い葉と合わせて剪定",
        text: "ハダニが出現。葉の状態が悪いものと合わせて剪定を実施。",
        photos: ["shiso_250727_1.jpg", "shiso_250727_2.jpg", "shiso_250727_3.jpg"],
      },
      {
        date: "8/2",
        tags: ["trouble", "fail", "grow"],
        title: "2株でハダニ大量発生・ポット株は終了・液肥実施",
        text: "2株でハダニが大量発生。ポットの株は状態が悪く終了とした。液肥を実施。",
        photos: ["shiso_250802_1.jpg", "shiso_250802_2.jpg", "shiso_250802_3.jpg"],
      },
      {
        date: "8/6",
        tags: ["harvest"],
        title: "収穫",
        text: "収穫。",
        photos: ["shiso_250806_1.jpg"],
      },
      {
        date: "8/8",
        tags: ["grow"],
        title: "液肥施行・最後の1株は虫もつかず順調",
        text: "液肥を施行。残る最後の1株は虫もつかず状態が良い。",
        photos: ["shiso_250808_1.jpg"],
      },
      {
        date: "8/16",
        tags: ["grow", "trouble"],
        title: "液肥施行・元気だが油断するとハダニ発生",
        text: "液肥を施行。元気に育っているが、気を抜くとすぐハダニが付く状態が続いている。",
        photos: ["shiso_260816_1.jpg"],
      },
      {
        date: "8/23",
        tags: ["harvest"],
        title: "収穫",
        text: "収穫。",
        photos: ["shiso_260823_1.jpg", "shiso_260823_2.jpg"],
      },
      {
        date: "8/28",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。",
        photos: [],
      },
      {
        date: "8/30",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["shiso_260830_1.jpg"],
      },
      {
        date: "9/2",
        tags: ["harvest"],
        title: "収穫",
        text: "収穫。",
        photos: ["shiso_260902_1.jpg"],
      },
      {
        date: "9/5",
        tags: ["grow"],
        title: "液肥施行",
        text: "液肥を施行。（※直近の天候は全体ログ参照）",
        photos: ["shiso_260905_1.jpg"],
      },
      {
        date: "9/11",
        tags: ["harvest", "grow"],
        title: "まだ収穫できそう・液肥施行",
        text: "まだ収穫できそうな状態。液肥を施行。",
        photos: ["shiso_260911_1.jpg"],
      },
    ],
  },

  {
    id: "cucumber",
    emoji: "🥒",
    name: "きゅうり",
    sub: "",
    color: "moss",
    status: "🏁 栽培終了（今期は収穫少なめで終了）",
    season: "2026年春蒔き",
    westRating: 3,
    basicData: [
      { key: "分類", val: "ウリ科" },
      { key: "空白期間（連作対策）", val: "2〜3年" },
      { key: "種子(好光or嫌光)", val: "嫌光" },
      { key: "種まき時期", val: "4〜5月" },
      { key: "定植時期", val: "5月" },
      { key: "収穫時期", val: "6〜9月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、有機質豊か" },
      { key: "株間目安", val: "40〜60cm" },
      { key: "推奨プランター", val: "深め：深さ30cm～" },
    ],
    points: [
      "本葉3枚になったら1〜2週に1回追肥",
      "定植後2〜3日は強い日差しに負けることがあるため様子を見る",
      "追肥は定植2週間後から液肥、2〜3週間後から化成肥料（2〜3週に1回。実が次々なる時期はこまめに）",
      "【摘芯】6節目までのわき芽はすべて除去",
      "7〜10節の子ヅルは葉を1枚残して先端を切る（この時の孫ヅルも葉を1枚残して先端を切る）",
      "11節目から先の子ヅルは葉を2枚残して先端を切る（孫ヅルは放置、混み合ったら先端のみ切る）",
      "主枝は25〜30節（高さ2m程度）で摘芯",
      "葉かき：収穫後の下葉や黄化葉、ハダニ被害葉はこまめに除去して風通しを良くする（1日2枚までが目安、多いとストレスになる）",
      "風通しが悪くなる大きな葉を切って新芽・新葉に光を当てるのも良い",
    ],
    warnings: [
      "水切れ注意！特に夏は朝・夕の1日2回水やり",
      "定植後2〜3日は強い日差しに注意（日陰で様子見）",
      "実が次々なる時期は追肥をこまめに",
      "13節目あたりまで開花・着果しても実が途中で萎れて落ちる事象が発生中（原因調査・経過観察中）",
    ],
    westNote: "西向きのため午後からの日照のみ。ネットに誘引して上方向へ伸ばし西日を最大限確保。",
    photos: [
      "cucumber_250621_1.jpg",
      "cucumber_250615_1.jpg",
    ],
    timeline: [
      { date: "5/24", tags: ["grow"], title: "苗を購入", text: "ホームセンターで苗を購入。", photos: [] },
      { date: "5/25", tags: ["grow"], title: "植付", text: "プランターに定植。定植後2〜3日は強い日差しを避けて様子見。", photos: [] },
      { date: "5/29", tags: ["grow"], title: "日当たりの良い場所へ移動", text: "根が落ち着いたためより日の当たる場所へ移動。", photos: [] },
      {
        date: "6/1",
        tags: ["grow"],
        title: "つるが伸び始め",
        text: "つるが伸び始め、葉も大きく広がってきた。ネットへの誘引準備中。",
        photos: ["cucumber_250601_1.jpg"],
      },
      {
        date: "6/7",
        tags: ["grow"],
        title: "つるが伸び始め・ネットに誘引開始",
        text: "つるが伸び始めたため、ネットへの誘引を開始。葉も大きく展開してきた。",
        photos: ["cucumber_250607_1.jpg"],
      },
      {
        date: "6/15",
        tags: ["grow"],
        title: "化成肥料・生育中・開花確認",
        text: "化成肥料を施用。ネットに誘引しながら上方向へ生育中。黄色い花も確認できる。",
        photos: ["cucumber_250615_1.jpg"],
      },
      {
        date: "6/21",
        tags: ["grow", "trouble"],
        title: "高さ約1m・13〜14節目に着果",
        text: "つるの高さが約1mに成長。13〜14節目に実がつき始めた。ただし13節目までも開花・着果はしていたが、途中で実が萎れて落ちてしまうケースが続いている。今回の実が無事育つか経過観察中。",
        photos: ["cucumber_250621_1.jpg", "cucumber_250621_2.jpg"],
      },
      {
        date: "6/22",
        tags: ["trouble"],
        title: "ベト病疑い・罹患葉を除去",
        text: "下葉を中心に黄白色の斑点が広がり、ベト病と思われる症状を確認。罹患している葉を5枚ほど切り落として処置。上部のつるは引き続き生育中。この日の気温28℃・湿度63%と高温多湿で、一気に被害が広がった印象。",
        photos: ["cucumber_250622_1.jpg", "cucumber_250622_2.jpg"],
      },
      {
        date: "6/24",
        tags: ["trouble"],
        title: "下葉を水霧吹きで洗浄",
        text: "水を入れた霧吹きで下葉を洗浄。胞子を洗い流し、感染拡大を抑える目的で実施。",
        photos: [],
      },
      {
        date: "6/25",
        tags: ["trouble"],
        title: "下葉をさらに4枚剪定",
        text: "症状が続いているため、下部の葉をさらに4枚剪定。風通しを改善して感染拡大を抑制。",
        photos: [],
      },
      {
        date: "6/27",
        tags: ["trouble"],
        title: "病気の葉を1枚剪定",
        text: "病気にやられていると思われる葉を1枚剪定。全植物への納豆菌液散布も同日実施（全体ログ参照）。",
        photos: [],
      },
      {
        date: "6/28",
        tags: ["trouble"],
        title: "葉を2枚剪定",
        text: "病気の症状が見られる葉を2枚剪定。上部のつるは引き続き生育中。",
        photos: ["cucumber_250628_1.jpg"],
      },
      {
        date: "7/3",
        tags: ["trouble"],
        title: "葉を1枚剪定・ベト病の前兆疑い",
        text: "葉に白っぽい斑点の前兆のようなものが現れたため、ベト病を警戒して1枚剪定。引き続き経過観察。",
        photos: [],
      },
      {
        date: "7/4",
        tags: ["trouble"],
        title: "病気拡散中・葉を3枚剪定",
        text: "黄白色の斑点が葉全体に広がっており、依然として病気が拡散中。葉を3枚剪定して対処。",
        photos: ["cucumber_250704_1.jpg"],
      },
      {
        date: "7/5",
        tags: ["trouble"],
        title: "アーリーセーフ散布・35節残して主枝摘芯",
        text: "病気の葉が依然1枚進行中。アーリーセーフを散布。35節を残して主枝を摘芯。19節目までは病気のため葉を切除しており、その影響でそれまでに着果していた実も枯れてしまった。梅雨で日照不足が続いていることも一因と思われる。",
        photos: [
          "cucumber_250705_1.jpg",
          "cucumber_250705_2.jpg",
          "cucumber_250705_3.jpg",
          "cucumber_250705_4.jpg",
        ],
      },
      {
        date: "7/5",
        tags: ["trouble"],
        title: "ダコニール1000を初回使用",
        text: "ベト病対策としてダコニール1000（1000倍希釈）を散布。使用1回目（総使用上限12回）。",
        photos: [],
      },
      {
        date: "7/7",
        tags: ["trouble"],
        title: "下部の葉に斑点再発・ダコニール1000を再散布",
        text: "下部の葉に斑点が再び現れたため、ダコニール1000をしっかり散布。使用2回目（総使用上限12回）。",
        photos: [],
      },
      {
        date: "7/12",
        tags: ["grow"],
        title: "化成肥料施行",
        text: "化成肥料を施行。上部の葉はきれいな状態で、摘芯後も新しい生育が進んでいる。",
        photos: ["cucumber_250712_1.jpg", "cucumber_250712_2.jpg"],
      },
      {
        date: "7/15",
        tags: ["trouble"],
        title: "まだら模様が再発した葉を1枚切除",
        text: "1枚がまだら模様化したため切除。引き続き経過観察。",
        photos: ["cucumber_250715_1.jpg"],
      },
      {
        date: "7/16",
        tags: ["grow"],
        title: "実が大きく育ち始め・収穫期待",
        text: "ようやく1本が大きく育ち始めた。順調にいけば収穫まで育ちそう。",
        photos: ["cucumber_250716_1.jpg"],
      },
      {
        date: "7/19",
        tags: ["trouble", "grow"],
        title: "実が収穫サイズに・頭頂部の葉が枯れる（ハモグリバエ疑い）",
        text: "実がようやく収穫できそうなサイズに育った。一方で頭頂部の葉が枯れており、ハモグリバエの被害と思われる症状を確認。上部の葉に特に被害が目立つ。",
        photos: ["cucumber_250719_1.jpg"],
      },
      {
        date: "7/20",
        tags: ["harvest", "trouble"],
        title: "1本初収穫（今期累計1本）・上部の葉を剪定",
        text: "1本を初収穫。今期の収穫累計は1本。上部の葉の状態が良くないため剪定を実施。",
        photos: ["cucumber_250720_1.jpg", "cucumber_250720_2.jpg", "cucumber_250720_3.jpg"],
      },
      {
        date: "7/27",
        tags: ["fail"],
        title: "今期栽培終了",
        text: "実がなりそうな様子が見られなくなったため、今期のきゅうり栽培はこれで終了とする。",
        photos: ["cucumber_250727_1.jpg", "cucumber_250727_2.jpg"],
      },
    ],
  },

  {
    id: "tomato",
    emoji: "🍅",
    name: "ミニトマト",
    sub: "",
    color: "bark",
    status: "🏁 栽培終了（今期は8/31で終了）",
    season: "2026年春蒔き",
    westRating: 3,
    basicData: [
      { key: "分類", val: "ナス科" },
      { key: "空白期間（連作対策）", val: "3〜4年" },
      { key: "種子(好光or嫌光)", val: "嫌光" },
      { key: "種まき時期", val: "4～5月" },
      { key: "定植時期", val: "4〜5月" },
      { key: "収穫時期", val: "6〜10月" },
      { key: "最適な土の性質", val: "弱酸性〜中性、有機質豊かで通気性良好" },
      { key: "株間目安", val: "40〜50cm" },
      { key: "推奨プランター", val: "深め：深さ30cm～" },
    ],
    points: [
      "【追肥】定植後2〜3週間から開始",
      "化成肥料は2週に1回、または液肥を週1回",
      "葉が内側に巻いていたら肥料過多のサイン",
      "【わき芽かき】5mm以下の小さいうちに行う",
      "6段目の花房の上に葉を2枚残して摘芯（高さ1.5m程度が目安）",
      "【摘葉】収穫済みの段より下の葉は風通しのため順次除去",
      "病気や黄化した葉はすぐに除去",
      "【水やり】均一にしないと実割れの原因になる。夏は朝たっぷり与え、夕方は土の状態を見て判断",
      "【収穫】果実全体が色づいたら収穫",
      "ヘタの付け根まで色づき、指で軽く押して少し弾力があるくらいが食べ頃",
      "ヘタ付近に「離層（割れ目）」が入り始めたら採り頃をやや過ぎている",
      "東京の夏（8月）は連続収穫ラッシュのため毎日チェックする",
      "採り遅れると裂果（実が割れる）の原因になる",
      "【高温対策】7〜8月に最高気温35℃超が続くと花が落ちることがある（高温障害）",
      "遮光率20〜30%の遮光ネットで午後2〜4時の直射を少し遮ると改善する",
    ],
    warnings: [],
    westNote: "西向きのため午後からの日照のみ。支柱で高い位置へ誘引し西日を最大限確保して管理中。",
    photos: [
      "tomato_250615_1.jpg",
    ],
    timeline: [
      { date: "5/29", tags: ["grow"], title: "購入・定植", text: "苗を購入し、プランター1つに定植。", photos: ["tomato_250529_1.jpg"] },
      { date: "6/1", tags: ["grow"], title: "日当たりの良い場所へ移動・わき芽かき", text: "より日の当たる場所へプランターを移動。初回のわき芽かきを実施。小さな実も確認できる。", photos: ["tomato_250601_1.jpg"] },
      {
        date: "6/7",
        tags: ["grow"],
        title: "スパイラル支柱で誘引中・生育順調",
        text: "支柱に沿って上方向へ誘引しながら順調に生育中。",
        photos: ["tomato_250607_1.jpg"],
      },
      {
        date: "6/15",
        tags: ["grow"],
        title: "生育中・スパイラル支柱で誘引・開花確認",
        text: "スパイラル支柱で上方向へ誘引しながら生育中。黄色い花も確認できる。",
        photos: ["tomato_250615_1.jpg"],
      },
      {
        date: "6/19",
        tags: ["grow"],
        title: "わき芽かき・液肥実施・高さ約60cm・4段目花房確認",
        text: "高さ約60cmに成長。花節が4つ目まで出てきた。わき芽かきと液肥を実施。",
        photos: ["tomato_250619_1.jpg"],
      },
      {
        date: "6/24",
        tags: ["grow"],
        title: "支柱を2mに変更",
        text: "背丈が伸びてきたため、支柱を約2mのものに変更。今後もしっかり上方向に誘引していく。",
        photos: [],
      },
      {
        date: "6/28",
        tags: ["grow"],
        title: "化成肥料追肥",
        text: "化成肥料を追肥。黄色い花も確認でき、引き続き上方向へ生育中。",
        photos: ["tomato_250628_1.jpg"],
      },
      {
        date: "7/5",
        tags: ["harvest", "grow", "trouble"],
        title: "実が色づき始め・6段目花房・葉ダニ発生でアーリーセーフ散布",
        text: "実が赤く色づき始めるものが出てきた。6段目の花房も出てきたため、そろそろ摘芯の時期。摘芯の際は先端側に葉（枝）を2つ残す予定。葉の裏にハダニが発生するようになり、アーリーセーフの散布と霧吹きで対処。",
        photos: ["tomato_250705_1.jpg"],
      },
      {
        date: "7/10",
        tags: ["harvest"],
        title: "初収穫（2個）",
        text: "赤く色づいた実を2個初収穫。",
        photos: [],
      },
      {
        date: "7/12",
        tags: ["grow"],
        title: "化成肥料施行",
        text: "化成肥料を施行。実も次々とついており、旺盛に生育中。",
        photos: ["tomato_250712_1.jpg"],
      },
      {
        date: "7/15",
        tags: ["trouble"],
        title: "ハダニ被害が目立ち葉水実施",
        text: "紫蘇と並んでハダニの被害が目立つ状態。全体の葉水散布で対処。",
        photos: [],
      },
      {
        date: "7/16",
        tags: ["trouble", "harvest"],
        title: "ハダニ被害葉の剪定・実が増加",
        text: "ハダニ被害や色が悪い葉を剪定。色づいた実も増えてきており、収穫が進んでいる。",
        photos: ["tomato_250716_1.jpg", "tomato_250716_2.jpg"],
      },
      {
        date: "7/19",
        tags: ["harvest"],
        title: "3個収穫（今期累計5個）",
        text: "赤く色づいた実を3個収穫。今期の収穫累計は5個。",
        photos: ["tomato_250719_1.jpg", "tomato_250719_2.jpg", "tomato_250719_3.jpg"],
      },
      {
        date: "7/27",
        tags: ["harvest", "trouble"],
        title: "2個収穫・葉ダニ再発で葉水",
        text: "2個収穫。葉ダニが再び出現したため、葉水で対処。",
        photos: ["tomato_250727_1.jpg", "tomato_250727_2.jpg", "tomato_250727_3.jpg", "tomato_250727_4.jpg"],
      },
      {
        date: "8/2",
        tags: ["trouble"],
        title: "アーリーセーフ散布",
        text: "アーリーセーフを散布。",
        photos: ["tomato_250802_1.jpg"],
      },
      {
        date: "8/7",
        tags: ["harvest"],
        title: "8個収穫（今期累計15個）",
        text: "8個収穫。今期の収穫累計は15個。",
        photos: ["tomato_250807_1.jpg", "tomato_250807_2.jpg"],
      },
      {
        date: "8/16",
        tags: ["grow"],
        title: "化成肥料施行",
        text: "化成肥料を施行。",
        photos: ["tomato_260816_1.jpg"],
      },
      {
        date: "8/18",
        tags: ["harvest"],
        title: "5個収穫（今期累計20個）",
        text: "5個収穫。今期の収穫累計は20個。",
        photos: ["tomato_260818_1.jpg"],
      },
      {
        date: "8/23",
        tags: ["trouble"],
        title: "花落ちが多い・葉色濃く外側に垂れ下がる",
        text: "花が落ちてしまうことが多い気がする。葉色が濃いことと葉が外側に巻いて垂れ下がっていることから、栄養過剰や日照不足の影響ではないかと考えている。今年の気温は一昨年・昨年と比べて低めなので、高温による被害は大きくないのではないかと思う。",
        photos: [],
      },
      {
        date: "8/30",
        tags: ["grow"],
        title: "生育中",
        text: "",
        photos: ["tomato_260830_1.jpg"],
      },
      {
        date: "8/31",
        tags: ["harvest", "fail"],
        title: "3個最終収穫・今期栽培終了",
        text: "実がなりそうもないため今期の栽培を終了。最後に3個収穫。今期の収穫累計は23個。",
        photos: ["tomato_260831_1.jpg"],
      },
    ],
  },
];

// タグの表示名と色（基本このままでOK）
const TAGS = {
  seed:    { label: "種まき",  cls: "seed" },
  grow:    { label: "生育",    cls: "grow" },
  harvest: { label: "収穫",    cls: "harvest" },
  trouble: { label: "トラブル", cls: "trouble" },
  flower:  { label: "開花",    cls: "flower" },
  fail:    { label: "失敗",    cls: "fail" },
};

// 全体ログ（時系列のできごと）
const LOG = [
  // {
  //   date: "9/29",
  //   tags: ["seed"],
  //   title: "秋作スタート",
  //   text: "しゅんぎく・そら豆・スナップを播種。",
  //   photo: "log_0929.jpg",
  // },
  {
    date: "2025/10/3〜10/7",
    tags: ["seed"],
    title: "秋作スタート（パセリ・春菊・サンチュ・ルッコラ・そら豆・スナップエンドウ）",
    text: "2025年秋蒔きの種まきをスタート。パセリ（10/3夜浸水・10/4種まき）、サンチュ（10/3夜スポンジへ種まき、水耕栽培）、春菊・ルッコラ・そら豆・スナップエンドウ（各10/7種まき）。",
    photo: "log_251005_parsley_sanchu_seedbed.jpg",
  },
  {
    date: "2025/10/7",
    tags: ["grow"],
    title: "種まき時期の気温・週間予報",
    text: "本日は曇り（最高25℃・最低20℃）。明日8日は雨予報（最高26℃・最低19℃）。その後1週間程度も曇り・雨がちの予報。秋まき（パセリ・春菊・サンチュ・ルッコラ・そら豆・スナップエンドウなど）の種まき時期の記録として残す。",
    photo: "log_251007_weather.jpg",
  },
  {
    date: "6/26",
    tags: ["grow"],
    title: "納豆菌培養液を作成",
    text: "水500ml＋納豆3粒＋きび糖小さじ1をヨーグルトメーカーで6時間培養して納豆菌液を作成。翌日の全植物への散布に備える。",
    photo: "",
  },
  {
    date: "6/27",
    tags: ["grow"],
    title: "全植物に納豆菌液を散布",
    text: "前日に培養した納豆菌液を全ての植物に散布。300mlにペットボトルキャップ1杯分程度の濃度に希釈して使用。病害菌への拮抗作用による病気予防・生育促進を期待。",
    photo: "",
  },
  {
    date: "7/5",
    tags: ["trouble", "grow"],
    title: "アーリーセーフ散布・梅雨の日照不足続く",
    text: "きゅうり・ミニトマト・メロンにアーリーセーフを散布。6月中旬頃から梅雨で曇天・雨天が続き、ほぼ日光が当たらない状態が続いている。日照不足が生育や病害の遠因になっている可能性がある。",
    photo: "",
  },
  {
    date: "7/5",
    tags: ["trouble"],
    title: "ダコニール1000購入・きゅうりに使用（1回目）",
    text: "ダコニール1000（TPN水和剤、30ml、664円）を購入し、きゅうりのベト病対策に使用開始。使用基準：きゅうり1000倍・収穫前日まで・総使用12回まで／ミニトマト1000倍・収穫前日まで・総使用2回まで／メロン700〜1000倍・収穫3日前まで・総使用5回まで。【使用回数】きゅうり1回目。",
    photo: "log_250705_daconil.jpg",
  },
  {
    date: "7/7",
    tags: ["trouble"],
    title: "ダコニール1000をきゅうりに再使用（2回目）",
    text: "きゅうり下部の葉に斑点が再発したため、ダコニール1000を再度散布。【使用回数】きゅうり2回目／上限12回。",
    photo: "",
  },
  {
    date: "7/12",
    tags: ["trouble", "grow"],
    title: "全植物に葉水散布（蓄圧式スプレー）",
    text: "バジルなど一部でハダニの発生が見られたため、蓄圧式スプレーを使って全植物に葉水を実施。ハダニ対策として継続していく予定。",
    photo: "",
  },
  {
    date: "7/15",
    tags: ["trouble"],
    title: "全植物に葉水を再実施・紫蘇とミニトマトで被害目立つ",
    text: "紫蘇とミニトマトで特にハダニ被害が目立ったため、全植物に葉水を再度実施。",
    photo: "",
  },
  {
    date: "7/16",
    tags: ["grow"],
    title: "モロヘイヤ・ルッコラの土を再生へ",
    text: "撤去したモロヘイヤの土は、湿らせて透明ビニール袋に入れ天日で消毒。ルッコラの土は乾燥させてから根を取り除き、再利用の準備を進める。",
    photo: "log_250716_soil1.jpg",
  },
  {
    date: "7/20",
    tags: ["trouble"],
    title: "ダニ太郎を初使用（きゅうり・ミニトマト・メロン）",
    text: "毎日のように葉裏へ葉水を行っているがハダニが消えないため、ダニ太郎（20ml計量容器付）をきゅうり・ミニトマト・メロンに施行。",
    photo: "log_250720_danitaro.jpg",
  },
  {
    date: "7/23",
    tags: ["grow"],
    title: "ダニ太郎の効果でハダニがほぼ消える",
    text: "毎日一枚一枚葉裏へ葉水をしていてもすぐに発生していたハダニが、ダニ太郎の効果か、ほぼ見られなくなった。",
    photo: "",
  },
  {
    date: "8/16",
    tags: ["grow"],
    title: "毎晩の水揚げ葉水を継続中",
    text: "毎晩、水揚げ葉水を実施。特にミニトマト・メロン・紫蘇・バジルを重点的に。パセリはハダニ被害が大きく復活するか不明なため、葉水は控えめにしている。",
    photo: "",
  },
  {
    date: "8/20",
    tags: ["grow"],
    title: "モロヘイヤ・ルッコラ・きゅうりの土再生作業",
    text: "再生・消毒中のモロヘイヤの土（約6L）に苦土石灰11gを施行。苔のようなものが生えてきたため黒いビニールで覆った。再生中のルッコラの土（4L）は苦土石灰8gを施行し、再度日光消毒。きゅうりの土は根っこ・微塵土を除去し、湿らせて透明ビニールで日光消毒を開始。",
    photo: "",
  },
  {
    date: "9/1",
    tags: ["grow"],
    title: "元ルッコラ・モロヘイヤ・きゅうりの土に再生剤・土袋で保管",
    text: "元ルッコラ・モロヘイヤ・きゅうりの土に再生剤を投入し、土袋で保管。元肥はまだ入れていない。",
    photo: "",
  },
  {
    date: "9/5",
    tags: ["grow"],
    title: "この一週間曇り続き・気温低め",
    text: "9/5午前10時頃の気温は21℃。この一週間はずっと曇りで、気温も冷房をほぼ使う必要がない程度に低い。",
    photo: "",
  },
  {
    date: "9/11",
    tags: ["grow"],
    title: "曇り・雨続き、気温低め（本日は最高21℃予想）",
    text: "この一週間も曇りや雨が続き、30℃を超えた日は1〜2日程度だった。本日の最高気温は21℃予想。",
    photo: "",
  },
];

// 費用記録：date は "YYYY-MM-DD" 形式（正確な日付が不明な場合はシーズン代表日を使用）
// category は「種苗」「用具」「用土」「肥料・薬」「その他」の5種から選択
// 例: { date: "2026-09-15", category: "用土", item: "培養土 14L", amount: 980, vegetableId: "melon", note: "" }
const EXPENSES = [
  // ★2025年春蒔き（日付不明のためシーズン代表日 4/1）
  { date: "2025-04-01", category: "用具", item: "園芸クリップ", amount: 110, note: "" },
  { date: "2025-04-01", category: "用具", item: "きゅうりネット", amount: 110, note: "" },
  { date: "2025-04-01", category: "肥料・薬", item: "化成肥料", amount: 689, note: "" },
  { date: "2025-04-01", category: "種苗", item: "きゅうり苗", amount: 100, vegetableId: "cucumber", note: "" },
  { date: "2025-04-01", category: "用具", item: "エンビパイプ柵", amount: 3260, note: "" },
  { date: "2025-04-01", category: "用具", item: "噴霧器", amount: 1399, note: "" },
  { date: "2025-04-01", category: "用土", item: "パーライト", amount: 110, note: "" },
  { date: "2025-04-01", category: "用具", item: "鉢底石", amount: 110, note: "" },
  { date: "2025-04-01", category: "肥料・薬", item: "ハダニ用薬", amount: 801, note: "" },

  // ★2025年秋蒔き（日付不明のためシーズン代表日 10/1）
  { date: "2025-10-01", category: "用具", item: "コンテナ", amount: 220, note: "" },
  { date: "2025-10-01", category: "種苗", item: "春菊・サンチュ種", amount: 110, note: "" },
  { date: "2025-10-01", category: "用土", item: "ハイドロボール", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "両面テープ", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "アルミシート", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "鉢底ネット", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "ECメーター", amount: 652, note: "" },
  { date: "2025-10-01", category: "用土", item: "パーライト", amount: 110, note: "" },
  { date: "2025-10-01", category: "用土", item: "バーミキュライト", amount: 110, note: "" },
  { date: "2025-10-01", category: "用土", item: "ピートモス", amount: 110, note: "" },
  { date: "2025-10-01", category: "種苗", item: "そら豆・スナップエンドウ種", amount: 110, note: "" },
  { date: "2025-10-01", category: "肥料・薬", item: "ハイポネックス微粉200g", amount: 688, note: "" },
  { date: "2025-10-01", category: "肥料・薬", item: "ハイポネックス再生材5L", amount: 820, note: "" },
  { date: "2025-10-01", category: "用土", item: "腐葉土バーク入り14L", amount: 394, note: "" },
  { date: "2025-10-01", category: "用土", item: "苦土石灰2kg", amount: 233, note: "" },
  { date: "2025-10-01", category: "用土", item: "硬質鹿沼土5L", amount: 330, note: "" },
  { date: "2025-10-01", category: "用土", item: "赤玉小粒14L", amount: 382, note: "" },
  { date: "2025-10-01", category: "用具", item: "土用シート", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "透明シート", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "ネット2枚", amount: 220, note: "" },
  { date: "2025-10-01", category: "用具", item: "円形洗濯ネット42×52", amount: 220, note: "" },
  { date: "2025-10-01", category: "用具", item: "円形洗濯ネット42×54", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "90Lゴミ袋", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "120Lゴミ袋", amount: 110, note: "" },
  { date: "2025-10-01", category: "用具", item: "銀ラック（25×45cm）×2と部品", amount: 1760, note: "" },
  { date: "2025-10-01", category: "用具", item: "洗濯ネット", amount: 110, note: "" },

  // ★2026年春蒔き（日付不明のためシーズン代表日 4/1）
  { date: "2026-04-01", category: "種苗", item: "サンチュ・パセリ・モロヘイヤ・ニラの種", amount: 220, note: "" },
  { date: "2026-04-01", category: "種苗", item: "唐辛子の苗", amount: 100, vegetableId: "chili", note: "" },
  { date: "2026-04-01", category: "種苗", item: "きゅうりの苗", amount: 100, vegetableId: "cucumber", note: "" },
  { date: "2026-04-01", category: "種苗", item: "ミニトマトの苗", amount: 165, vegetableId: "tomato", note: "" },
  { date: "2026-04-01", category: "肥料・薬", item: "ダニコール1000", amount: 664, note: "" },
  { date: "2026-04-01", category: "肥料・薬", item: "ダニ太郎", amount: 962, note: "" },

  // ★2026年秋蒔き
  { date: "2026-09-16", category: "種苗", item: "つるありスナップ・早どり小松菜の種", amount: 110, note: "" },
];
